### ISSUE TITLE
Doesn't show memory temperature

### ISSUE THREAD

**Issue by weskraft2203** [rigelminer/rigel#100]
Updated drivers. On version 528.49 the memory temperature was. On versions 545.92, 546.01 there is no memory temperature.
![Uploading 51599638_MINIG-PC9112023_91245.png…]()

**Comment by weskraft2203** [comment]
![1](https://github.com/rigelminer/rigel/assets/143587163/4cd3206c-9be1-49a6-be8d-6ee49acb8877)

**Comment by rigelminer** [comment]
Fixed in 1.12.0
