### ISSUE TITLE
Add option to remove ANSI codes

### ISSUE THREAD

**Issue by thewizard1002** [rigelminer/rigel#103]
Please add an option to disable ansi codes when running this from cmd

**Comment by rigelminer** [comment]
ANSI codes are used for displaying the terminal user interface (TUI). You can disable it by running the miner with `--no-tui`. Let me know if that helps.

**Comment by thewizard1002** [comment]
Using --no-tui works on the local machine, but it still shows ANSI codes when you use PSEXEC and run it remotely on another machine.
![image](https://github.com/rigelminer/rigel/assets/42820195/b7e34767-c8f3-4c21-a878-50333a5f343f)

**Comment by rigelminer** [comment]
Oh, right, I completely forgot about colour reset sequences.
The only way to prevent ANSI codes in the terminal would be to disable any colour in it (like yellow warning and red error lines would be white) - would that work for you? If so, I can add a `--no-colour` option.

**Comment by thewizard1002** [comment]
That would probably work just fine.  Thanks!

**Comment by rigelminer** [comment]
Added `--no-colour` in 1.15.0
