### ISSUE TITLE
Titan V Nexa "architecture (70) is not supported"

### ISSUE THREAD

**Issue by MadMax56rus** [rigelminer/rigel#104]
Please add Titan V support on Nexa.
![Снимок экрана 2023-12-03 131415](https://github.com/rigelminer/rigel/assets/124651386/bbce6445-cb04-4fc7-a0a3-bb179287ef66)

**Comment by rigelminer** [comment]
I had trouble compiling Nexa for arch70, so excluded that architecture altogether. Will need to look into it and see if I can fix it. Can't give you an ETA unfortunately.

**Comment by MadMax56rus** [comment]
Thanks. I will be grateful if support for the Volta architecture appears in the miner soon)

**Comment by rigelminer** [comment]
Added in 1.10.1. If you face any issues please let me know.
