### ISSUE TITLE
CUDA error on old graphic card

### ISSUE THREAD

**Issue by pIvan** [rigelminer/rigel#106]
You probably don't plan to fix this issue, but perhaps you have a solution. I'm trying to run Rigel on 2 SLI GTX 760 and I'm getting the error 'GPU#0 error: CUDA error: architecture (30) is not supported'.

Thank you in advance

**Comment by rigelminer** [comment]
Oh, GTX 760 is an old architecture and isn't supported by Rigel, sorry, I'm afraid you'll need to use another miner.
