### ISSUE TITLE
Please add conflux+ironfish dual mode

### ISSUE THREAD

**Issue by Grey-Makarov** [rigelminer/rigel#109]
Please add conflux+ironfish dual mode

**Comment by rigelminer** [comment]
I'm afraid I won't be adding CFX+IRON because IronFish project is going to change the algorithm to FishHash very soon, so it's not worth the effort. Hope you understand.

**Comment by rigelminer** [comment]
I'm afraid I won't be adding CFX+IRON because IronFish project is going to change the algorithm to FishHash very soon, so it's not worth the effort. Hope you understand.

**Comment by rigelminer** [comment]
I'm afraid I won't be adding CFX+IRON because IronFish project is going to change the algorithm to FishHash very soon, so it's not worth the effort. Hope you understand.
