### ISSUE TITLE
cfx mining hive option overvalue loose phenomenon

### ISSUE THREAD

**Issue by cutestor1** [rigelminer/rigel#110]
If you put an overvalue in the rigel minor live option, it recognizes the overvalue at first and returns to its default value after about 5 seconds.
What is the reason for the release?

--cclock 210 --lock-cclock [1]1470 --mclock [1]1100 --fan-control [1]70 --kernel 2

**Comment by rigelminer** [comment]
Sorry, I don't understand the meaning of "overvalue" in this context. Are you referring to the fan speed?
