### ISSUE TITLE
The miner does not reset its settings for WIN after it is closed

### ISSUE THREAD

**Issue by Regiven123** [rigelminer/rigel#111]
The miner does not reset its settings for WIN after it is closed.  Other miners reset the settings by closing the command line "ctrl+x" and then you can work under WIN without problems. Now the situation is deplorable, you need to restart the PC, and this is not very pleasant when you have to do it at least 5 times. Is there any way to reset the settings? Can you add a reset command to the miner "ctrl+x"?

**Comment by rigelminer** [comment]
The miner is supposed to reset the OC to the original values that were set prior to launching the miner. If you believe there is a bug, try this:
1. Reboot
2. Add `--log-file rigel.log` to the list of parameters you run rigel with
3. Start the miner
4. Terminate the miner gracefully by sending Ctrl+C to the terminal

**Comment by Regiven123** [comment]
Перепроверил информацию, да, после настройки клавиатуры клавиши ctrl+c работает, майнер закрывается, НО, настройки вbдеокарты не передаются заводским под системой WIN. Сброс настроек Afterburner не помогает, только новая перезагрузка возвращает видеокарту к нормальному состоянию.
Вот если что как выглядит Bat-файл:
@echo off
@cd /d "%~dp0"
rigel.exe -a karlsenhash ^
   -o stratum+ssl://eu.karlsen.k1pool.com:5212   -u Wallet ^
   --cclock 200 ^
   --lock-cclock 1680 ^
   --lock-mclock 810 ^
   -w RigName --log-file logs/miner.log

**Comment by rigelminer** [comment]
> reset the OC to the original values that were set prior to launching the miner

Please note that the stock settings and "the original values that were set prior to launching the miner" are not the same thing. The log file should indicate what OC is applied when it exits.

**Comment by Regiven123** [comment]
Please explain what needs to be done?

**Comment by rigelminer** [comment]
There's no functionality in Rigel to reset the OC to stock after exit. The miner does reset the OC to whatever it was when you started the miner. If you launched the miner when the OC was stock, it will reset it to stock after exit. Hope that makes sense.

**Comment by Aloprinha** [comment]
We need a command to reset it to default, same as other miners.
