### ISSUE TITLE
miner not working

### ISSUE THREAD

**Issue by cgds1907** [rigelminer/rigel#114]
[2023-12-19 00:58:43] CUDA error: failed to load CUDA: LoadLibraryExW failed
[2023-12-19 00:58:43] miner terminated

not working on windows
i updated latest driver 
what is the problem might be

**Comment by rigelminer** [comment]
Are your cards Nvidia or AMD? Have you tried running mining software other than rigel?

**Comment by cgds1907** [comment]
i have both cards and i did mine till pyrin coin .
couldnt run pyrin on both lolminer and rigel

thx for answer

**Comment by rigelminer** [comment]
In that case it's probably something wrong with your system environment. Try reinstalling the driver. I'm going to close the issue as it's not something I can fix in Rigel, but feel free to post your findings here.
