### ISSUE TITLE
Skydoge

### ISSUE THREAD

**Issue by slavaover** [rigelminer/rigel#115]
When will you add the skydoge algorithm?

**Comment by rigelminer** [comment]
Do you have any information about this algorithm? Open source miner maybe?

**Comment by slavaover** [comment]
unfortunately, no, there is only one WildRig Multi miner running on it, but I don't like it.

**Comment by slavaover** [comment]
If something works out, I can help with testing, I have several 4090 cards

**Comment by slavaover** [comment]
https://github.com/nujia2017/ccminer/releases

**Comment by rigelminer** [comment]
Thanks but the miner your linked is closed source. I'll keep an eye on the project though.

**Comment by slavaover** [comment]
Please also show interest when you add the memehash algorithm.

**Comment by slavaover** [comment]
Greetings, if it's not difficult, take a look at the SHA256 DT algorithm, NOVO coin

**Comment by rigelminer** [comment]
Skydoge support in not planned
