### ISSUE TITLE
SUPER LOW HASHRATE IN REGIL MINER FOR PYRIN

### ISSUE THREAD

**Issue by Chubs21** [rigelminer/rigel#118]
Hi I have been using Regil Miner for a little while and for the past 3 to 4 days my hashrate has drooped significantly. I was getting 12 to 15 GH/s and would stay consisitant until the problem started . Now im getting from 2 to 7 GH/s and it jumps around like crazy. I also noticed that my computer was running a sold 174.6 with barley any flux then after the issue it jumps around also from 60 to 170 and does not stay stable... someone please help?
IS there some way to update or something ?? I've never had this issue before...
Im using the rtx 4090 with intel i9 13th gen 13900

**Comment by rigelminer** [comment]
No one else has reported such issue so far so I'm assuming it's hardware related. Have you tried reducing the overclock, power limit?

**Comment by Chubs21** [comment]
Yes I have it's super odd I don't understand it I even went back to default
and no change. And it's even Lower. Can I update it or something?  What
else would cause this to happen?

**Comment by rigelminer** [comment]
I know it's been a while, but I was wondering if you're still experiencing it? Is the GPU used to drive the display as well mining?
