### ISSUE TITLE
Not work on SSL when use port forwarding

### ISSUE THREAD

**Issue by HerbertLi2020** [rigelminer/rigel#119]
windows 10

I use cloud servers for port forwarding,
Use SSL link (rigel.exe -a karlsenhash -o stratum+ssl://....... ）

The mining pool link was unsuccessful.
connection error: presented server name type wasn't supported

The connection can be successful using TCP.

On lolMiner, SSL can be successfully linked.

Why?

**Comment by rigelminer** [comment]
Most miners don't validate TLS certificates whereas Rigel does so by default. To disable the validation use `--no-strict-ssl`. Let me know if you manage to connect to your stratum server.

**Comment by HerbertLi2020** [comment]
It is worked.

**Comment by HerbertLi2020** [comment]
It is working well by using --no-strict-ssl .
thank you very much.

**Comment by rigelminer** [comment]
Thanks for letting me know.
