### ISSUE TITLE
RTX4090 1.3.5 low hashrate

### ISSUE THREAD

**Issue by MadMax56rus** [rigelminer/rigel#12]
v 1.3.4: RTX 4090 cclck 2220, mem +2000, power 400W, 220 MH/s
![RTX4090_1_3_4](https://user-images.githubusercontent.com/124651386/217169060-5a266df8-f6a4-49f8-aac5-ebc608db19d5.jpg)
v 1.3.5: RTX 4090 cclck 2220, mem +2000, power 300W, <180 MH/s and no longer grows
![RTX4090_1_3_5](https://user-images.githubusercontent.com/124651386/217169115-59add3c5-c8c6-45e3-9958-b7480f42d2ba.jpg)

**Comment by rigelminer** [comment]
Thanks for reporting. It is a known issue and I'm hoping to get it fixed within the next few days.

**Comment by rigelminer** [comment]
Fixed in 1.3.6
