### ISSUE TITLE
CUDA error: error code 101 with Rigel 1.12.0 (4070ti)

### ISSUE THREAD

**Issue by artemstepa** [rigelminer/rigel#122]
Hi, 
I've hit a snag while mining with Rigel 1.12.0 on my two rigs with 4070ti. I'm consistently running into a CUDA error code 101. 
Any insights or fixes on this? Really appreciate the help!

**Comment by rigelminer** [comment]
For reference: `CUDA_ERROR_INVALID_DEVICE = 101`.
Had you been using Rigel successfully for a while when the error appeared, or has it never worked?

**Comment by artemstepa** [comment]
The error appears several minutes after lauching the miner. As an axample, I launched it today and please find the miner/application/system logs. Maybe, it helps to understand the issue.
<img width="704" alt="system_log" src="https://github.com/rigelminer/rigel/assets/139461757/3db8b27e-2294-4067-96f1-e32e9bec6c45">
[application log.txt](https://github.com/rigelminer/rigel/files/13793001/application.log.txt)
<img width="287" alt="Cuda101" src="https://github.com/rigelminer/rigel/assets/139461757/aa3c392b-a2a2-4cf1-b8d0-00747c7af79a">

**Comment by rigelminer** [comment]
Does reboot help? Looks like a driver or hardware issue.

**Comment by artemstepa** [comment]
Reboot helps and miner works for 30-50min. But after the next error, miner runs in a loop = only manual reboot is possible. I use raveos 1.0.26 (2220) which is with nvidia-525.147.05. Hardware ASRock B450 Pro4 R2.0 + AMD Ryzen 3 1200 Quad-Core Processor.
With lolminer, there is no such issue.

**Comment by artemstepa** [comment]
Yes, it works: 18 hours of stable work with a decreased core offset. Thank you!

**Comment by rigelminer** [comment]
You're welcome. If it's a multi-GPU rig, you probably need to decrease the offset only for one GPU. From your screenshot above it's the one that has PCI address 07:00.0.

**Comment by artemstepa** [comment]
Yes.. Experimenting with 07:00.0 now. Thank you!

**Comment by artemstepa** [comment]
The issue stemmed from compatibility problems when operating a 4070ti GPU on AMD motherboards (three different models were tested). The problem was resolved by transitioning to INTEL motherboards. The consistently stable performance over the past three weeks has validated the assumption.
