### ISSUE TITLE
The memory temperature for 2070 super has disappeared since version 1.12.0 on all drivers.

### ISSUE THREAD

**Issue by Megavolt2024** [rigelminer/rigel#126]
The memory temperature for 2070 super has disappeared since version 1.12.0 on all drivers. Windows 10.

**Comment by mralemao** [comment]
In the new driver 551.23 with a 3070 TI and on Windows, rigelminer 1.14.0 does not display the temperature. GPU-z is normal.

**Comment by mralemao** [comment]
> The memory temperature for 2070 super has disappeared since version 1.12.0 on all drivers. Windows 10.

Do you see the temperature in GPU-z ?

**Comment by Megavolt2024** [comment]
In the latest GPU-Z version, the memory temperature at 2070 super has also disappeared.

**Comment by mralemao** [comment]
Maybe it's a measurement problem on the 2070s cards, but here on the 3070ti the temperature is normal on GPU-z. Let's hope that maybe a correction for the 30 series will help in the 20 series.

**Comment by rigelminer** [comment]
Memory temps display is fixed on 550+, but I'm afraid it won't do anything for 2070s
