### ISSUE TITLE
a lot of reject shares on the kawopow algorithm on nicehash

### ISSUE THREAD

**Issue by Sun1-nxt** [rigelminer/rigel#128]
When using Rigel 1.13.0 on nicehash kawpow there are a lot of rejected shares (50%) . rejected shares do not appear immediately, but after a couple of hours. 
Use -a kawpow 
cmp 50hx hiveos 525.85.05

**Comment by ikorzha** [comment]
I second that issue. I have notices overtime when switches the coins in nicehash it appears to be that rigel miner "doesn't recognize some of the of the coins" and rejects all shares.  Than I have observed that later on when coin switch  again and shares are once again accepted.
Please identify the issue and correct it if possible. I use 3070, 3080 and 3090s on nicehash KawPOW algo..

**Comment by rigelminer** [comment]
Thank you. I am currently testing the fix for this issue.

**Comment by rigelminer** [comment]
Fixed in 1.13.1
