### ISSUE TITLE
6xRTX3070Ti 1.3.5 insufficient memory

### ISSUE THREAD

**Issue by MadMax56rus** [rigelminer/rigel#13]
Rig 6xRTX3070Ti does not work with version 1.3.5. Error at startup on all 6 video cards "insufficient memory"
![log](https://user-images.githubusercontent.com/124651386/217192467-e5187b01-9803-4694-86df-b0498e89ade2.jpg)
on version 1.3.4 everything works fine.

**Comment by rigelminer** [comment]
Could you run the miner on just one GPU and see if starts up? For example, run with `-d 0`.

**Comment by MadMax56rus** [comment]
I tried it and the error is the same. Any number of active cards results in this error.

**Comment by MadMax56rus** [comment]
I have another computer with the same 3070 ti and it does not have this error.

**Comment by Kazantipi** [comment]
I have the same problem

**Comment by Archtersim** [comment]
same problem, only 3060ti and 3070 on windows (3080 and 3080 ti on windows is fine, every card on linux is fine)

**Comment by Polytemp** [comment]
version 1.3.5, 1.3.6 . 3070 ti "insufficient memory".

**Comment by artdekortim** [comment]
[2023-02-17 08:35:10] GPU#11: lookup tables built
[2023-02-17 08:35:10] GPU#0: lookup tables built
[2023-02-17 08:35:10] GPU#9: lookup tables built
[2023-02-17 08:35:10] GPU#6: lookup tables built
[2023-02-17 08:35:10] GPU#4: lookup tables built
[2023-02-17 08:35:10] GPU#3: lookup tables built
[2023-02-17 08:35:10] GPU#7: lookup tables built
[2023-02-17 08:35:10] GPU#5: lookup tables built
[2023-02-17 08:35:10] GPU#10: lookup tables built
[2023-02-17 08:35:10] GPU#8: lookup tables built
[2023-02-17 08:35:22] GPU#10 error: insufficient memory
[2023-02-17 08:35:22] GPU#1 error: insufficient memory
[2023-02-17 08:35:22] GPU#2 error: insufficient memory
[2023-02-17 08:35:22] GPU#7 error: insufficient memory
[2023-02-17 08:35:22] GPU#3 error: insufficient memory
[2023-02-17 08:35:22] GPU#11 error: insufficient memory
[2023-02-17 08:35:22] GPU#0 error: insufficient memory
[2023-02-17 08:35:22] GPU#4 error: insufficient memory
[2023-02-17 08:35:22] GPU#8 error: insufficient memory
[2023-02-17 08:35:22] GPU#9 error: insufficient memory
[2023-02-17 08:35:22] GPU#6 error: insufficient memory
[2023-02-17 08:35:23] GPU#5 error: insufficient memory

12Х3060ti at any acceleration both in the miner and in the autoburner.

10х3070ti work well.

**Comment by MadMax56rus** [comment]
1.3.7 still same problem.

**Comment by artdekortim** [comment]
12Х3060ti error: insufficient memory
rigel-1.3.7-win

**Comment by tjayz** [comment]
No one seems to have questioned what your current virtual memory is at since you are on windows. If you have 12 3060ti where there are 8gb memory per gpu then your minimum virtual memory should be set to 36gb and max should be 96gb, although wouldn't hurt to try higher for testing purposes. Try increasing virtual memory to the sum of your gpu ram.
system>AdvancedSytemSettings>performance>advanced>change>custom

**Comment by MadMax56rus** [comment]
I have 64Gb virtual memory with 6*3070ti and it didn't help. I increased the virtual memory to 96 GB and didn't help either. I think this is a bug.

**Comment by tjayz** [comment]
Someone above mentions all cards work fine in linux. While this may not be related to what the user sets virtual memory too, seems highly probable it is related to virtual memory somehow, specifically on the GDDR6 8gb cards, while GDDR6X seems unaffected. Just thought I'd ask since no one else mentions it in thread.

Same issue here https://github.com/rigelminer/rigel/issues/20

**Comment by tjayz** [comment]
> I have another computer with the one same 3070 ti and it does not have this error. But this is not a rig this is a working computer

Do the separate computers run on different versions and or builds of windows?

**Comment by MadMax56rus** [comment]
Rig 6*3070ti - windows 10 Pro 1903
work computer 3070ti - windows 10 Pro 21H1

**Comment by tjayz** [comment]
I would update to 21H1 to rule it out as cause. 
Win+r>gpedit.msc>Computer Configuration > Administrative Templates > Windows Components > Windows Update > Windows Update for Business>21H1 > run windows update. 

You could run a script such as sledgehammer to block all other updates if thats why you still on the older version.

**Comment by MadMax56rus** [comment]
> I would update to 21H1 to rule it out as cause. Win+r>gpedit.msc>Computer Configuration > Administrative Templates > Windows Components > Windows Update > Windows Update for Business>21H1 > run windows update.
> 
> You could run a script such as sledgehammer to block all other updates if thats why you still on the older version.

Thank you very much! I update to 21H2 and it works.
