### ISSUE TITLE
ergo+iron Computing power is unstable

### ISSUE THREAD

**Issue by tolygbaby** [rigelminer/rigel#131]
ergo+iron, the computing power of ergo is normal, but the computing power of iron is not stable and changes up and down (as shown in the picture); it is normal when set under gminer, but I want to use rigel.

--cclock 300 --lock-cclock 1560 --lock-mclock 5001 --no-strict-ssl

<img width="892" alt="1" src="https://github.com/rigelminer/rigel/assets/107846733/3b85ae01-fec6-4b42-b120-2bc1adcbb595">
<img width="923" alt="2" src="https://github.com/rigelminer/rigel/assets/107846733/8657ffca-72de-4f39-a719-117f38c4ee5d">

**Comment by rigelminer** [comment]
This is normal and caused by ERG dataset prebuilds - during that period the miner spends extra compute resources on building the dataset for the next block, so the secondary algo (ironfish) takes a hit. It's the same with any other miner, except some display it as a hashrate drop and some don't.

**Comment by tolygbaby** [comment]
Thanks
