### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by jackson82009** [rigelminer/rigel#134]
![image](https://github.com/rigelminer/rigel/assets/157903707/849711a0-f75b-476e-8bb8-973159f28d5e)
Seems to be stuck like this, no error message, nothing. Waited roughly 5 minutes still nothing. any ideas?

**Comment by rigelminer** [comment]
Following the discussion in Discord, is it correct that you aren't experiencing this on the latest version and the issue can be closed?

**Comment by jackson82009** [comment]
yes
