### ISSUE TITLE
abel unexpected EOF

### ISSUE THREAD

**Issue by derhier** [rigelminer/rigel#135]
When connecting to ABEL pool with RIGEL i am getting an unexpected EOF Error

Running Hiveos. running various Nvidia Cards

**Comment by rigelminer** [comment]
This is a very common issue, it's caused by not setting TLS on in your flightsheet 
![image](https://github.com/rigelminer/rigel/assets/119491468/62772ccd-4450-433c-b55d-60a8716572f3)

**Comment by derhier** [comment]
Thanks, worked.
