### ISSUE TITLE
Opting out of automatic memory clock resetting

### ISSUE THREAD

**Issue by amoiseev** [rigelminer/rigel#138]
> [Rigel 1.13.1](https://github.com/rigelminer/rigel/releases/tag/1.13.1)
> Set GPU memory clock offset to 0 when building DAG to prevent its corruption

Could you please add an option to disable this?

I am integrating Rigel miner into Kryptex desktop mining app, some users using Afterburner overclocking are not expecting this behavior.

**Comment by UselessGuru** [comment]
> Could you please add an option to disable this?

Agree. There should be an option to tell the miner to not overclock and use whatever clocks were set when the miner was started.

**Comment by rigelminer** [comment]
Sounds good. The next version will have it.

**Comment by rigelminer** [comment]
Added `--dag-reset-mclock on/off` in 1.15.0
