### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by MadMax56rus** [rigelminer/rigel#142]
Hi. v1.14.2 RTX 4070 with disabled 980Ti, miner uses a lot of CPU.
![Снимок экрана 2024-02-20 113140](https://github.com/rigelminer/rigel/assets/124651386/71b7d998-88a6-475d-b297-44f0ed66e24a)

**Comment by rigelminer** [comment]
Disabling HAGS should fix it, see https://github.com/rigelminer/rigel/issues/7#issuecomment-1445651292

**Comment by rigelminer** [comment]
Duplicate of https://github.com/rigelminer/rigel/issues/7
