### ISSUE TITLE
miner Keep restarting it self every 10 second

### ISSUE THREAD

**Issue by saat111** [rigelminer/rigel#143]
hello , the miner was working flawlessly 10 days in row without single restart , I haven't touch any setting including update of drivers or hiveos kernel I didn't touch any of this , now it's keep restarting miner and say dev fee error , after this I upgrade to latets stable nvidia driver also update kernel and all kind of oc low medium or high and I changed almost all versions of miner , nothing works and miner keep restarting every 10 second of mining ,I would be grateful if you could help , thank you
![IMG_4274](https://github.com/rigelminer/rigel/assets/65358969/f0fa3073-29aa-4857-b39c-91602be317ad)

**Comment by rigelminer** [comment]
Could you please post a screenshot with the error? The one in your message says the miner was terminated by the user pressing Ctrl+C (or some external application that sent a termination signal to rigel).

**Comment by saat111** [comment]
hello , unfortunately I can't take screen shot of it it's not showing any log in my monitor the only thing I can see it from local ip panel like this one not sure if it's help or not 
dev fee connectivity error: all pools are unavailable [2024-02-12 11:57:46] gpu#3: core offset set to +0 [2024-02-12 11:57:46] gpu#3: locked core set to 1470 [2024-02-12 11:57:46] gpu#6: core offset set to +0
at first I thought it's because of Teamredminer but I Run the Rigel in single flightsheet so I'm sure there is no other app to conflict, I really need to use Rigel because of more Hashrates and less power using

**Comment by rigelminer** [comment]
The dev fee connectivity error occurs when the miner can't establish a network connection to any of the dev fee servers (currently there are three), so try to see if there has been a network or firewall config change recently - at the time when the error started occurring. This can also be caused by your ISP blocking certain connections.

**Comment by saat111** [comment]
Hello , you were right when connection goes through VPN it's not restarting anymore , so it's clearly blocked by ISP , thanks for your quick response .

**Comment by rigelminer** [comment]
Thanks for getting back to me, I'm glad you figured it out. I'm also going to add SOCKS5 proxy support in the next version, it may be useful in your case too.
