### ISSUE TITLE
Fan control. Windows.

### ISSUE THREAD

**Issue by Megavolt2024** [rigelminer/rigel#145]
Hello. Please, is it possible to make the fans work in auto mode with factory settings on some cards, and manually select the fan mode on some? And if we closed the manner, then the next time we started, the fan settings worked again by default. Now we have to restart the computer so that they reset.

**Comment by rigelminer** [comment]
> is it possible to make the fans work in auto mode with factory settings on some cards, and manually select the fan mode on some?

Yes, e.g. `--fan-control _,_,50,50` - fan is managed by OS/driver (auto) for GPU 0 and 1, and set to 50% for GPU 2 and 3

> And if we closed the manner, then the next time we started, the fan settings worked again by default.

When the miner is stopped using Ctrl+C it resets fan control settings to what they were when the miner started. If the fan was "auto" the miner will make it "auto" upon terminating.

**Comment by Megavolt2024** [comment]
> When the miner is stopped using Ctrl+C it resets fan control settings to what they were when the miner started. If the fan was "auto" the miner will make it "auto" upon terminating.

When I press ctrl +c, the window does not close, and the miner restarts simply.

**Comment by rigelminer** [comment]
Something must be restarting the miner then. If you're using bat files to launch the miner, make sure there are no loops in it.

**Comment by Megavolt2024** [comment]
I have 30% on one card by default, and 50% on the second. If I set 10% for them, then the first one turns 30%, and the second one starts 41%. Nothing less.

**Comment by Megavolt2024** [comment]
I have 30% on one card by default, and 50% on the second. If I set 10% for them, then the first one turns 30%, and the second one starts 41%. Nothing less.
