### ISSUE TITLE
Will IronFish hardfork be supported?

### ISSUE THREAD

**Issue by amoiseev** [rigelminer/rigel#148]
https://ironfish.network/learn/blog/2024-02-26-testnet-hardfork

**Comment by rigelminer** [comment]
Yes

**Comment by amoiseev** [comment]
@rigelminer Hello, I see you've added `fishhash` support in version 1.15.0.

Will `--algorithm ironfish` auto-switch to `fishhash` upon hardfork?
If not, could you please add this behavior?
If anybody needs to pin the old algorithm, it would make sense to expose it as `--algorithm ironfish-blake3`.

I'm integrating your miner into the Kryptex mining app, and auto-switch-upon-hardfork functionality makes it much easier.

**Comment by rigelminer** [comment]
Hi, having an auto-switch would be problematic. The fork is scheduled to occur on block 503338 and ironfish mining pools don't send the block height information to mining clients, so the miner has no way of knowing when to switch unless I add some extra logic to query ironfish API. In addition to that, most users configure their overclock through miner params and they would need to somehow pass different OCs to the miner along with potentially different pool urls. There may be some other obstacles I overlooked. In other words, auto-switch is doable but I don't think it's worth the effort.
