### ISSUE TITLE
Does not work on windows 11 pro for workstations (insider preview).

### ISSUE THREAD

**Issue by SidorSidoroff** [rigelminer/rigel#15]
Does not work on windows 11 pro for workstations (insider preview). The miner version 1.3.1 works fine. Miner 1.3.4 and 1.3.5 don't even start. OS settings are the same in all cases. Nvidia graphics cards , driver 528.24. Algo nexapow.

**Comment by rigelminer** [comment]
What is the error message? Could you attach screenshots? Thanks.

**Comment by rigelminer** [comment]
Sorry I couldn't figure this out at the time. Now that the final release of Windows 11 is out and Rigel has had quite a few updates, are you still affected by this issue?
