### ISSUE TITLE
ergo+alephium+zil  error 

### ISSUE THREAD

**Issue by weskraft2203** [rigelminer/rigel#151]
Startup errors. With the command --zil-cache-dag off it starts. When the zil session starts there is a reboot
[miner.log](https://github.com/rigelminer/rigel/files/14612039/miner.log)
[miner15.log](https://github.com/rigelminer/rigel/files/14612040/miner15.log)

**Comment by rigelminer** [comment]
This is likely an overclock issue as stated in the log. In the config you've got
```
-a autolykos2+alephium+zil
...
--lock-cclock [1]1540 ...
--lock-cclock [2]1605 ...
...
```
You're not setting OC for ZIL - it would have `[3]` as the prefix, for example `--lock-cclock [3]1605`, so first thing I'd try is fixing the OC config.

**Comment by weskraft2203** [comment]
If you run it first ergo+alephium. Then run ergo+alephium+zil. Everything works until reboot. The OS is the same everywhere. Problems only with RTX 3060. With cards RTX 4070 and RTX 3080 no problems.
[miner.log](https://github.com/rigelminer/rigel/files/14622786/miner.log)

**Comment by weskraft2203** [comment]
If you run it first ergo+alephium. Then run ergo+alephium+zil. Everything works until reboot. The OS is the same everywhere. Problems only with RTX 3060 .With cards RTX 4070 and RTX 3080 no problems.
[Uploading miner.log…]()

**Comment by rigelminer** [comment]
> Problems only with RTX 3060. With cards RTX 4070 and RTX 3080 no problems.

There is nothing unusual about it. Like I suggested, fix your overclock config first. You're setting `--lock-cclock [2]1605 ...` which has no effect whatsoever because the miner is ignoring the settings with `[2]` prefix. Only `[1]` and `[3]` should be used in your case. `[1]` for ERG+ALPH, and `[3]` for ZIL.

**Comment by weskraft2203** [comment]
Thank you for your patience. Everything worked.

**Comment by rigelminer** [comment]
No worries at all :+1: Glad I could help. Closing the issue.
