### ISSUE TITLE
cuda error: error code 34 ,Does it work correctly in docker ?

### ISSUE THREAD

**Issue by linjianshu** [rigelminer/rigel#153]
i run docker with ubuntu 20.04 cuda11.7 images but it does work correctly , need u help , thank u~

root@7f6ad01bfd99:/home# nvcc --version 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

root@7f6ad01bfd99:/home# ./rigel -a pyrinhash -o stratum+tcp://in.mining4people.com:13390 -u hoosat:qrtxxmkeq3yt763nk5u46l90gpjxfr78y8yu58v80qu5m53zu6w0cddeerfzs -w WORKER --no-tui --api-bind 127.0.0.1:5000 
watchdog started, pid: 98
[2024-03-15 10:30:10] Rigel v1.15.0 - [Linux]
[2024-03-15 10:30:10] 
[2024-03-15 10:30:10] CUDA error: error code 34
[2024-03-15 10:30:10] miner terminated
restarting the miner in 5 sec...
[2024-03-15 10:30:15] Rigel v1.15.0 - [Linux]
[2024-03-15 10:30:15] 
[2024-03-15 10:30:15] CUDA error: error code 34
[2024-03-15 10:30:15] miner terminated
restarting the miner in 5 sec...

**Comment by rigelminer** [comment]
I'm not familiar with Docker but from the CUDA documentation https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html:

> CUDA_ERROR_STUB_LIBRARY = 34
>
> This indicates that the CUDA driver that the application has loaded is a stub library. Applications that run with the stub rather than a real driver loaded will result in CUDA API returning this error.

Let me know if that helps

**Comment by linjianshu** [comment]
> I'm not familiar with Docker but from the CUDA documentation https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html:
> 
> > CUDA_ERROR_STUB_LIBRARY = 34
> > This indicates that the CUDA driver that the application has loaded is a stub library. Applications that run with the stub rather than a real driver loaded will result in CUDA API returning this error.
> 
> Let me know if that helps

thank u very much, as u say it does cause about cuda driver mapping between host and docker, i will try to figure it out. thank again!
