### ISSUE TITLE
Pyrin + Zil = 3060 laptop have very Low hashrate.

### ISSUE THREAD

**Issue by lynxchat4** [rigelminer/rigel#155]
Hello!

Rigel version 1.15 
Raveos

Pyrin + Zil = 3060 laptop have very Low hashrate. 4.1 MH/s per card. Usual hashrate must be 37.5 MH/s per card

3070Laptop work normal.

Zil cache no take any changes.

**Comment by rigelminer** [comment]
Low ZIL hashrate is usually caused by using suboptimal overclock settings or applying the settings incorrectly. Could you post the full log file?

**Comment by lynxchat4** [comment]
I test with defaul overclok. Realy, with default settings all work.
But 3060m is too hot with TDP when ZIL work normal.

Because real power is much more.
For example:
KawPow 110w in miner = 150w real
Pyrin        80w in miner = 150w real

How I can solve this problem?

**Comment by lynxchat4** [comment]
Thank you. I try to make it.
