### ISSUE TITLE
Pyrin connection error

### ISSUE THREAD

**Issue by TopRTX** [rigelminer/rigel#156]
Hi!

There is a next problem after miner just started:

│[2024-03-21 01:31:16] [pyi.2miners.com:2121] extranonce: f37e                                                         
││[2024-03-21 01:31:16] [pyi.2miners.com:2121] RPC request id 2 failed: Invalid address                                 
││[2024-03-21 01:31:16] [pyi.2miners.com:2121] connection error: unexpected EOF

Is there any way to fix it, please?

**Comment by rigelminer** [comment]
> `RPC request id 2 failed: Invalid address`

I'd suggest to double check your wallet address

**Comment by TopRTX** [comment]
> > `RPC request id 2 failed: Invalid address`
> 
> I'd suggest to double check your wallet address

There was a pool problem. I changed the pool and now it's ok. Thanks!
