### ISSUE TITLE
how to run rigel Pyi in ubantu?

### ISSUE THREAD

**Issue by ZokiJava** [rigelminer/rigel#164]
thanks

**Comment by rigelminer** [comment]
You need to download the linux version (tar.gz) of the miner, unpack it, edit the script for the coin you want to mine - put your wallet addresses and pool details in, and run it.

**Comment by rigelminer** [comment]
`sudo ./pyi.sh` if you plan on overclocking with miner parameters, or `./pyi.sh` if not

**Comment by ZokiJava** [comment]
Thank you!!Is there a website for overclocking parameters for 4070s

**Comment by rigelminer** [comment]
Yes, https://www.hashrate.no/gpus/4070s/PYI

**Comment by ZokiJava** [comment]
the script like that↓ ?
./rigel -a pyrinhash -o stratum+tcp://de.pyrin.herominers.com:1177 -u YOUR_PYI_WALLET -w my_rig --log-file logs/miner.log --cclock 400 --lock-cclock 2190 --lock-mclock 810 --pl 240

**Comment by rigelminer** [comment]
yes
