### ISSUE TITLE
DUAL IRON/RXD error

### ISSUE THREAD

**Issue by M0rT4L13** [rigelminer/rigel#166]
Hello ! 

i have this issue when i try to dual mining IRON/RXD 
![Capture d’écran 2024-03-26 120226](https://github.com/rigelminer/rigel/assets/121009175/87b46363-e964-4a96-a1ec-8974b3787956)

why ? 

this is the bat file (i hide my wallets numbers, but there are on the right place : 

@echo off
@cd /d "%~dp0"

:: replace the wallet addresses with your own

:: to manually balance GPU resources between primary and secondary algorithms
:: use `--dual-mode` parameter, e.g.
:: `--dual-mode a12:r0.1` - minimum impact on the primary algorithm
:: `--dual-mode a12:r32.0` - maximum impact on the primary algorithm

:: iron + rxd
rigel.exe -a fishhash+sha512256d ^
    -o [1]stratum+tcp://de.ironfish.herominers.com:1145 -u [1]mywallet ^
    -o [2]stratum+tcp://pool.vipor.net:5066             -u [2]mywallet ^
    -w my_rig --log-file logs/miner.log

pause

**Comment by rigelminer** [comment]
You can't mine `fishhash+sha512256d` at the moment because there is no coin that is using `fishhash` algorithm in its mainnet. This combo will be supported after the IronFish hard fork https://fips.ironfish.network/fips/fip-10-hardfork-1

**Comment by M0rT4L13** [comment]
Oh ok… in the release patch note of the last rigel version, i say the possibility to dual mine but didn’t know that will be effective soon.

do you know when the fork will be enable ? 14 april ?

I can solo mine Iron for the moment, after the fork,  i need to do something with the iron that i mined or all is automatic with the fork ?
