### ISSUE TITLE
OCs dont go back on fish hash w/zil

### ISSUE THREAD

**Issue by keithsavage777** [rigelminer/rigel#169]
Hello devs like to report. OCs dont go back on fish hash w/zil . I mostly use rigel miner. And all my ocs work with zil but also fishhash . It mines st the right hash rate on fh then after the zil it does not go back to normal hashrate. But lower. Thanks

**Comment by keithsavage777** [comment]
So I set my oc like the hobbest said and I get 39 mh with 1440. 1900. Pl 150 on both my 3070s and 3060tis.

**Comment by keithsavage777** [comment]
And after zil is done hash is 25mh instead of returning back to 39mh

**Comment by keithsavage777** [comment]
Thanks

**Comment by keithsavage777** [comment]
Thanks

**Comment by rigelminer** [comment]
Please run the miner with `--log-file rigel.log`, wait for this issue to show up, and upload the log file here. Thanks.

**Comment by Alan911Black** [comment]
> Please run the miner with `--log-file rigel.log`, wait for this issue to show up, and upload the log file here. Thanks.

any help on his issue? i have the same thing.
it was working fine and switched OK to fishhash, but after i closed the app are re-open it was not able to connect to the fish pool again.

**Comment by rigelminer** [comment]
@Alan911Black this is a different issue. Herominers retired their auto-switch logic, so you now need to replace `-a ironfish --enable-fork` with `-a fishhash`.
