### ISSUE TITLE
FishHash on Hicehash reconects

### ISSUE THREAD

**Issue by Perfy** [rigelminer/rigel#171]
> [2024-04-03 13:47:32] [fishhash.auto.nicehash.com:9200] connection error: unexpected EOF                                                   │
> [2024-04-03 13:47:32] [fishhash.auto.nicehash.com:9200] connecting...                                                                      │
> [2024-04-03 13:47:32] [fishhash.auto.nicehash.com:9200] connected

**Comment by rigelminer** [comment]
Having done a brief test, it appears to be a Nicehash issue where the server drops the connection after 30 seconds of inactivity from the mining client (e.g. the miner fails to find and submit a share within 30s). I recommend reporting it to the NH support team.
