### ISSUE TITLE
How to add multiple mining pool addresses as backup (single mining multiple mining pool addresses) under Windows? What is the format?

### ISSUE THREAD

**Issue by tolygbaby** [rigelminer/rigel#178]
How to add multiple mining pool addresses as backup (single mining multiple mining pool addresses) under Windows? What is the format?

**Comment by rigelminer** [comment]
Use as many `-o` parameters as there are pools, e.g.
```
-o stratum+tcp://<pool1> -o stratum+tcp://<pool2> -o stratum+tcp://<pool3> ...
```
`pool1` will be the primary one, and `pool2`, `pool3` etc. will be used as failovers.

**Comment by tolygbaby** [comment]
Thank you for your answer

rigelminer ***@***.***> 于 2024年4月23日周二 00:47写道：
