### ISSUE TITLE
I get really low Hashrate with Iron Fish vs other miners. v1.6.2

### ISSUE THREAD

**Issue by iamthefunky1** [rigelminer/rigel#180]
When I mine Iron Fish with Rigel 1.6.2, my hashrate is only 3 MH/s at 63.5 W using hashrate.no's recommended overclocks with an RTX3090.  Below is my miner setup.

:: mine to herominers medium overclocks
rigel.exe -a fishhash -o stratum+tcp://us2.ironfish.herominers.com:1145 -u mywalletaddress -w mypcname --cclock 250 --lock-cclock 1110 --mclock 1000 --pl 350 --log-file logs/miner.log

According to hashrate.no I'm suppose to be getting around 79 MH/s at 268 W.  To test this out, I installed lolMiner and SRBminer and ran Iron Fish with the same exact recommended overclocks, and with those miners I'm getting over 60 MH/s. 

Is there a problem with Rigel running the new fishhash algo?

I attached my miner.txt file.  You'll have to scroll thru to see iron because I also mine nexa, alph, & dynex with Rigel.

[miner.log](https://github.com/rigelminer/rigel/files/15187785/miner.log)

**Comment by rigelminer** [comment]
Note that your GPU memory is locked to 810mhz when you mine `fishhash`. I can think of two solutions:
1. Whenever you want to stop the miner, press Ctrl+C. If you click the X button, the miner will be terminated abruptly and won't get a chance to revert OC to the original values - I think this is what happened in your case when you stopped mining `alephium`.
2. Add `--lock-mclock X` to your `fishhash` OC to tell the miner to unlock the memory even if it is locked.

**Comment by iamthefunky1** [comment]
@rigelminer That fixed it.  I never knew Ctrl+C actually closed out the miner properly.   Adding in --lock-mclock X straightened it right out.  Thank you!
