### ISSUE TITLE
What about AMD GPU compatibitiy?

### ISSUE THREAD

**Issue by serqwa** [rigelminer/rigel#181]
I see compatibility list at the site https://rigel-miner.bz/ 
 
Nvidia GeForce GTX 1050 Ti
Nvidia GeForce GTX 1060
Nvidia GeForce GTX 1070
Nvidia GeForce GTX 1070 Ti
Nvidia GeForce GTX 1080
Nvidia GeForce GTX 1080 Ti
Nvidia GeForce RTX 2060
Nvidia GeForce RTX 2070
Nvidia GeForce RTX 2080
Nvidia GeForce RTX 2080 Ti
AMD Radeon RX 470
AMD Radeon RX 480
AMD Radeon RX 570
AMD Radeon RX 580
AMD Radeon RX 590
AMD Radeon VII
AMD Radeon RX Vega 56
AMD Radeon RX Vega 64

Is it correct? Do you support AMD GPU?

**Comment by rigelminer** [comment]
No, Rigel is an nvidia-only miner. The website you referred to is not an official website and has no affiliation with Rigel.

**Comment by serqwa** [comment]
understood, thanks
