### ISSUE TITLE
Rigel 1.17.0

### ISSUE THREAD

**Issue by PapaPirate** [rigelminer/rigel#186]
On Windows 11, a 4090 video card on a xel coin hashrate 330 after some time drops to 30. Please fix this problem

**Comment by arc-Mi** [comment]
Same on 3080. Dropping from 190 to 40

**Comment by rigelminer** [comment]
Could you please try 1.17.2 and let me know if the issue is still there? Thanks.

**Comment by arc-Mi** [comment]
> Could you please try 1.17.2 and let me know if the issue is still there? Thanks.

On this version no more problem

**Comment by PapaPirate** [comment]
On this version no more problem.Thanks!

сб, 18 мая 2024 г., 14:56 arc-Mi ***@***.***>:
