### ISSUE TITLE
Excuse me, can I use Solo mode to dig xels in version 1.17.0 of Rigel? I don't want to join the mining pool. If possible, how can I proceed? thanks

### ISSUE THREAD

**Issue by zsvvv** [rigelminer/rigel#187]
Excuse me, can I use Solo mode to dig xels in version 1.17.0 of Rigel? I don't want to join the mining pool. If possible, how can I proceed? thanks

**Comment by rigelminer** [comment]
Added solo support in 1.17.1, use `solo+tcp://<ip>:8080` to connect
