### ISSUE TITLE
update :how can i update my rigel on hive os

### ISSUE THREAD

**Issue by juanrambler** [rigelminer/rigel#189]
hello please can somebody help me to update my rigel miner on hiveos... if the last version its not available on hiveos.. like 1.17.2 ? iknow theres is a link un github but i don know how use it thwanks

**Comment by rigelminer** [comment]
Select version 1.17.1 in the flightsheet and let HiveOS update to it. Then run the following update command:

(remove tildas `~` if running HiveOS beta): `cd ~/tmp && rm -rf ~/tmp/rigel-1.17.2-linux/ && wget https://github.com/rigelminer/rigel/releases/download/1.17.2/rigel-1.17.2-linux.tar.gz && tar -xvf rigel-1.17.2-linux.tar.gz && miner stop && cp -rf ~/tmp/rigel-1.17.2-linux/rigel /hive/miners/rigel/1.17.1/ && rm -rf ~/tmp/rigel-1.17.2-linux/ && miner start`
