### ISSUE TITLE
(XEL) Performance degradated on windows 7.

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#190]
Hello! 
If you started XEL on win7... sometimes you have 70kh on 2070, sometimes 30 kh... 
if you run the miner several times, then each time there will be a different hashrate. Error ONLY on win7. I think it's some kind of card initialization problem. Is it possible to improve initialization somehow for win7?
thank you!

**Comment by Mihaxxi** [comment]
the cards are different. 2070, 2060, 3070.

**Comment by rigelminer** [comment]
Which miner version is it? If it's 1.17.2, is it happening with 1.17.0 or 1.17.1 too?

**Comment by Mihaxxi** [comment]
> Which miner version is it? If it's 1.17.2, is it happening with 1.17.0 or 1.17.1 too?

i found it on 17.1 and 17.2

**Comment by Mihaxxi** [comment]
some new pictures...
![image](https://github.com/rigelminer/rigel/assets/106633929/152ba995-910a-4968-b791-b84e0fef5bff)

**Comment by Mihaxxi** [comment]
![image](https://github.com/rigelminer/rigel/assets/106633929/98263479-8354-42d7-b459-b81098d47c5f)

**Comment by rigelminer** [comment]
Not sure what could be causing it. Try increasing virtual memory size.

**Comment by Mihaxxi** [comment]
> Not sure what could be causing it. Try increasing virtual memory size.

No it's different problem. Because all my rig have more than 140gb page file (240gb SSD).
Problem resolve only if you restart miner several times.
