### ISSUE TITLE
Issue mining Xelishash with Rigel 1.17.2

### ISSUE THREAD

**Issue by federicosnobohm** [rigelminer/rigel#191]
![Captura de pantalla_22-5-2024_10545_the hiveos farm](https://github.com/rigelminer/rigel/assets/35777568/63df15fd-2f27-44c6-b7a2-b9f072777fa7)

Hi all i get this blanck spaces mining xelis is this normal? thanks

**Comment by rigelminer** [comment]
I've been told it's a HiveOS issue. You can confirm by checking your pool or the miner logs on whether there are any interruptions.

**Comment by federicosnobohm** [comment]
> I've been told it's a HiveOS issue. You can confirm by checking your pool or the miner logs on whether there are any interruptions.

Ok Thanks!
