### ISSUE TITLE
Heads Up on MEM TEMP reporting failing with NVIDIA Driver 555.85

### ISSUE THREAD

**Issue by pbiorci** [rigelminer/rigel#192]
The VRAM temperature is no longer reported in RigerlMiner V1.17.2 with NVIDIA Driver 555.85

I was previously was running NVIDIA Driver 551.23 with RigelMiner V1.17.2 and MEM temp was reported.

Have gone back to NVIDIA Driver 551.23 to get this reporting returned to the console.

**Comment by rigelminer** [comment]
Fixed in 1.17.3

**Comment by pbiorci** [comment]
Thank you.
