### ISSUE TITLE
Differents results for XELIS with Rigel 1.17.2 for windows and linux

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#193]
Hi! 

We have differents results for XELIS with Rigel 1.17.2 for windows (different drivers and different system (win7 and win10)) and linux with the same settings.
For example:
3070 have 161 for linux and 147 for windows.
3060ti have 148 for linux and 137 for windows.

Why? Could you fixed it for windows? 
Thank you!

**Comment by rigelminer** [comment]
If you enable HAGS on Windows, you should get similar results to the linux version

**Comment by Mihaxxi** [comment]
> If you enable HAGS on Windows, you should get similar results to the linux version

thank you so much! but it's only for win10, right?

**Comment by rigelminer** [comment]
> thank you so much! but it's only for win10, right?

I know Win 10 and 11 have the HAGS switch, not sure about Win 7

> its affected for 2070 series?

Yes

**Comment by Mihaxxi** [comment]
thank you!! have a nice day!
