### ISSUE TITLE
--lock-mclock

### ISSUE THREAD

**Issue by RGScalpers** [rigelminer/rigel#194]
Hello, using RVN and PYi (and others too) I cannot limit the memory to intermediate values ​​between 5000 and the maximum that gives 11200...

In the cmd it does say that it limits it but in the status bar it is still at 11251 (the maximum)

It happens to me in all currencies, I use W11 Rigel 1.17.2 Driver 552.44 on an RTX4080 Super

**Comment by rigelminer** [comment]
Not all frequencies are supported, run `nvidia-smi -i 0 -q -d SUPPORTED_CLOCKS` for the list of clocks you can use with `--lock-mclock`
