### ISSUE TITLE
Change % dual mining

### ISSUE THREAD

**Issue by RGScalpers** [rigelminer/rigel#195]
Hello, I want to use dual mining ERG+PYI.
When activated, almost all the power is directed to ERG about 80-90% and PYI 10-20%

I would like it to be the other way around but I haven't been able to add it correctly, even though the instructions seem easy. Could you give me an example?

rigel.exe -a autolykos2+pyrinhash ^
    -o [1]stratum+tcp://erg.2miners.com:8888 -u WALLET ^
    -o [2]stratum+tcp://pyi.2miners.com:2121 -u WALLET ^
    -w RTX4080S --log-file logs/miner.log
    --lock-cclock 2400 --lock-mclock 1000
    --temp-limit tc[60-75]
    --temp-limit tm[70-85]

**Comment by rigelminer** [comment]
Use `--dual-mode a12:rXXX`. Set `XXX` to smaller or bigger values depending on what PYI/ERG hashrate ratio you prefer. For example, `--dual-mode a12:r56` will make your PYI hashrate 56x of ERG.
