### ISSUE TITLE
Different hash each start

### ISSUE THREAD

**Issue by MarioCoarasa** [rigelminer/rigel#197]
I have 6 x 3090. The hash rate on each GPU is different 4 - 5%, but on a new start different GPU get more hash. 
P.e. first start 435, 455, 435, 435, 455, 435 and on a new start 455,435,435, 455, 455, 455.
It seem the auto tune is not consistent. 
Are there any chance to fix the auto tune?
Thanks in advance.

**Comment by rigelminer** [comment]
I'm aware of this issue but I haven't figured out how to fix it yet. What overclock settings are you using for your 3090s, and what OS are you running?

**Comment by rigelminer** [comment]
Thank you. I assume you're using HiveOS built-in OC capabilities to overclock the cards? Could you please try OCing with miner params and let me know if it helps with the issue? Thank you.
params to add: `--cclock 240 --lock-cclock 1680 --mclock 1300` (mem offset must be half of what you set in HiveOS)

**Comment by MarioCoarasa** [comment]
Done, Twice.
first     440,440, 440,*455*,440,440
second 440,440,*455*, 440,440,440

**Comment by rigelminer** [comment]
I wonder if `--lock-cclock 1680` may be too high and the GPUs are hitting the power limit during tuning - this would screws up the results. Would you mind trying to set it lower (`--lock-cclock 1600`) and seeing if you'd be getting more consistent hashrate across the runs?

**Comment by MarioCoarasa** [comment]
I did the test with CCOff240, LCClock 1600, MemClock 2000
But i got the same result, in this case 422,422,*440*,440,440,440 at first
test
                                                      422,422,*422*,440,440,440
second test

**Comment by MarioCoarasa** [comment]
Now I'm working at full speed and these are the results
This actualization is realy great, I just want to advise the problem
detected in order for you to have feedback, and perhaps, improve your miner
as always.
Greetings.

**Comment by sergneo** [comment]
I confirm that on win 10 with HUGS enabled on 4 x 3060 ti, the same problem occurs, every time you restart different hashrates on different cards, you have to restart 10 times to achieve the maximum. overclocking --lock-cclock 1500 --lock-mclock 5000. 
is there any way to do auto tuning manually?

**Comment by rigelminer** [comment]
I'll add a parameter to apply tuning values manually in one of the future versions (possibly the next one)

**Comment by rigelminer** [comment]
Unfortunately I can't fix the auto-tuner but I added `--tune` parameter in 1.17.4 for you to be able to lock in the tuning values and get the same hashrate every time the miner is started

**Comment by sergneo** [comment]
Thanks for adding the parameter. And what are these numbers measured in?
Example:
 --tune 184,_,320

**Comment by rigelminer** [comment]
Those are some internal parameters and I don't want to assign any meaning to them right now because it may change in future.
I'm going to quote one of the users from our Discord server that summarises how you're supposed to use `--tune` pretty well:
> Check what tuning values the auto-tuner assigned to your cards when you start up and add them to your config. This way the next time you launch/restarts the miner it skips the tuning process and have consistent hashrate across miner restarts. 
you can also play around with it a bit. give it +10 -10 and see whats best

You only really need to use those if you notice you have a few identical cards that end up with different hashrate (see the first message in this github ticket). In that case just use the value that results in the better performance.
