### ISSUE TITLE
Miner dont work at HIVE OS

### ISSUE THREAD

**Issue by federimau** [rigelminer/rigel#198]
Last released version 1.17.3 dont work at HIVE. Im using linux link released at flight sheet (https://github.com/rigelminer/rigel/releases/download/1.17.3/rigel-1.17.3-linux.tar.gz) but miner do not start.
Thanks in advance

**Comment by federimau** [comment]
i tried installing manually but dont work in hive

**Comment by rigelminer** [comment]
1.17.3 is now available in HiveOS
