### ISSUE TITLE
Tip for Windows users: turn on HAGS

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#201]
Hello, dear developer!

I have a question about hashing speed in win7. Now that win7 has no HAGS options...
My rigs with win7 are very far from my location. 
How much is it possible to improve the speed (in new versions of you great miner) for 1660 super and 1660ti cards for xelis in win7?
Thank you very much for you time!

Best regards,
Mikle.

**Comment by rigelminer** [comment]
Hi Mikle, on a Windows system unequipped with HAGS I don't think there is a way to make XEL hashrate match Win10/11. With HAGS off there is some overhead I can't get rid of, unfortunately. Migrating to Linux or Win10/11 would be your best bet. Windows 7 is an old OS, even Rust (the programming language Rigel is written in) has recently dropped support for it, so eventually I will have to do the same.

**Comment by Mihaxxi** [comment]
ok. understood.

**Comment by rigelminer** [comment]
@Mihaxxi I feel your pain. Like WinXP before it, Windows 7 was a great OS and it comes as no surprise people are still using it after almost 15 years since its initial release. However, the world (and Microsoft as part of it, haha) has moved on, and so must we.

**Comment by Mihaxxi** [comment]
> @Mihaxxi I feel your pain. Like WinXP before it, Windows 7 was a great OS and it comes as no surprise people are still using it after almost 15 years since its initial release. However, the world (and Microsoft as part of it, haha) has moved on, and so must we.

There's something you should know. initially, I had on win10 rigs with 1660 cards, but I switched them to win7 due to the fact that win10 took up a lot of video memory (the problem of the ETH DAG file). Apparently now we'll have to transfer everything back. The only question is that these rigs are far away...
