### ISSUE TITLE
XEL hashrate 

### ISSUE THREAD

**Issue by claude339** [rigelminer/rigel#202]
Why is the hash rate of the same overclocking setting in windows version so different between win 11 and win 10?

![1717382217379](https://github.com/rigelminer/rigel/assets/156056897/24c2f24b-b321-4f63-a010-f3a36be92612)
![1717382190904](https://github.com/rigelminer/rigel/assets/156056897/bf9eafab-d9a8-4124-b6a4-01a1713bb2de)

**Comment by rigelminer** [comment]
You probably have HAGS off in Win 10. To turn it on:
> On Windows 10, head into Settings > System > Display > Graphics Settings and toggle on "Hardware-Accelerated GPU Scheduling." On Windows 11, navigate to Settings > System > Display > Graphics > Change Default Graphics Settings and enable "Hardware-Accelerated GPU Scheduling."

**Comment by rigelminer** [comment]
Oh, and you're running different versions of the miner by the way

**Comment by claude339** [comment]
sir, enable Hardware-Accelerated GPU Scheduling and same miner version the problem is still, I've basically tried all

**Comment by claude339** [comment]
Hardware-Accelerated GPU Scheduling setting is right?
![1717397582392](https://github.com/rigelminer/rigel/assets/156056897/d6b6d6aa-4ce4-49b3-869f-d27396aea368)

**Comment by rigelminer** [comment]
I can't read that language, but if I remember correctly the HAGS settings dialog should look like this
![image](https://github.com/rigelminer/rigel/assets/119491468/8b9df863-f9b8-463e-935d-965716b81164)

**Comment by claude339** [comment]
oh, win 10 pro no such option, only select program
![image](https://github.com/rigelminer/rigel/assets/156056897/6a4cba75-6cc7-47c9-bf7a-02e2ffb43484)

**Comment by rigelminer** [comment]
Your win 10 is probably not up to date, the HAGS switch wasn't there initially

**Comment by claude339** [comment]
OK, thank you very much. I will mine other
