### ISSUE TITLE
Cannot mining on linux

### ISSUE THREAD

**Issue by vutd1122** [rigelminer/rigel#204]
![Screenshot_20240607-110245_Samsung Internet](https://github.com/rigelminer/rigel/assets/75006245/623bf6c1-9222-4985-b193-5cae04826efa)
![Screenshot_20240607-110731_Samsung Internet](https://github.com/rigelminer/rigel/assets/75006245/4a6a3712-4c62-450e-a678-30fa1aa4233a)

Hello, I face this issue when I try 1.17.4
1.17.3 is working fine
Please help me

**Comment by rigelminer** [comment]
Try re-downloading the miner. I heard this issue may be caused by the disk damage (in your case it's a USB stick which makes it even more likely).

**Comment by vutd1122** [comment]
Test on 10 rigs, have same issue, I dont think it is usb issue. Is this driver version suitable: nv525.125.06c11.8?

**Comment by rigelminer** [comment]
Yes, the driver is fine. What's the SHA256 checksum of the rigel executable on your rig?
```
sha256sum /var/lib/repomining/miner/rigel-1.17.4/rigel
```

**Comment by vutd1122** [comment]
> Yes, the driver is fine. What's the SHA256 checksum of the rigel executable on your rig?
> 
> ```
> sha256sum /var/lib/repomining/miner/rigel-1.17.4/rigel
> ```

Sorry, I cannot check because of mining os does not have this function but i know the download url as following:
https://download.vhttos.com/miner_org/rigel-1.17.4.tar.gz
https://download.vhttos.com/miner_org/rigel-1.17.4.tar.gz.md5

**Comment by rigelminer** [comment]
The checksum of `rigel` binary from the archive you liked to (https://download.vhttos.com/miner_org/rigel-1.17.4.tar.gz) doesn't match that of the one I published on github. Even the file size doesn't match (77537792 vs 84140208 bytes). I recommend you  reach out to the support of your mining OS and ask them to look into it.
