### ISSUE TITLE
getting job timeout error

### ISSUE THREAD

**Issue by truckinCowboy** [rigelminer/rigel#205]
For the life of me can't figure out how to fix this.
I have tried other pools still same thing and i've tried shutting off my firewall etc in case but still no good

[miner.log](https://github.com/user-attachments/files/15747608/miner.log)

**Comment by rigelminer** [comment]
Tried connecting from my end, and it worked just fine. Could also be the antivirus blocking connections.

**Comment by truckinCowboy** [comment]
I disabled my antivirus and tried it still doesnt work

**Comment by truckinCowboy** [comment]
Ok found the issue it was my router was blocking it.
Thank you for your help.
