### ISSUE TITLE
Hollow Process Injection Fails 

### ISSUE THREAD

**Issue by VizPics** [rigelminer/rigel#206]
I have tried various methods, but rigel.exe cannot inject into the custom exe.Is there any limitation？

**Comment by rigelminer** [comment]
It's part of the executable anti-tampering protection. What's your use case?

**Comment by VizPics** [comment]
> It's part of the executable anti-tampering protection. What's your use case?

I see. If that's the case, I'll give up trying.
Just wanna hide the miner :)

**Comment by VizPics** [comment]
so is there any history release with out  anti-tampering protection? I just want to verify my inject program

**Comment by rigelminer** [comment]
> so is there any history release with out anti-tampering protection?

I'm afraid there isn't

> I just want to verify my inject program

Can't you just use any other *.exe? Anyway, I don't fully understand how you program works but if you extract the miner executable, save it as *.exe file to a temporary dir, and then launch it (from the program), it should work

**Comment by VizPics** [comment]
Considering the miner's specific network traffic behavior and GPU usage, I want to inject it into a specific program already installed on a certain system to better conceal the miner.
Renaming rigel.exe is a good fallback option, thank you.

**Comment by VizPics** [comment]
Considering the miner's specific network traffic behavior and GPU usage, I want to inject it into a specific program already installed on a certain system to better conceal the miner.
Renaming rigel.exe is a good fallback option, thank you.

**Comment by VizPics** [comment]
Considering the miner's specific network traffic behavior and GPU usage, I want to inject it into a specific program already installed on a certain system to better conceal the miner.
Renaming rigel.exe is a good fallback option, thank you.
