### ISSUE TITLE
Disable OC FULLY!

### ISSUE THREAD

**Issue by megalolka** [rigelminer/rigel#212]
Hi!
Please make an option to FULLY disable overclocking.
I don't want the miner to spend my computing power to set overclocking. I use other nvidia tools to set it!

**Comment by rigelminer** [comment]
Assuming you're mining a DAG-based algorithm, `--dag-reset-mclock off` makes the miner not touch OC at all. If you're looking at resetting the OC to factory settings, use `rigel --reset-oc`.

**Comment by megalolka** [comment]
Thank you, this parameter works!
