### ISSUE TITLE
ubuntu系统如何启动rigel ?

### ISSUE THREAD

**Issue by laowu002** [rigelminer/rigel#214]

**Comment by rigelminer** [comment]
You need to unpack the miner archive, edit the relevant `*.sh` script and start it e.g. `./iron.sh`

**Comment by laowu002** [comment]
Thank you!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月16日(周二) 下午2:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rigelminer/rigel] ubuntu系统如何启动rigel ? (Issue #214)




 
Closed #214 as completed.
