### ISSUE TITLE
RPC request id 155 timed out

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#215]
For any coins i have this error. (i'v tested from many pools)

connection error: RPC request id 155 timed out
connecting...
connected

**Comment by rigelminer** [comment]
This error indicates that the miner did not receive a response to a submitted share within 10 seconds - could be a pool issue but based on the info you provided is likely an ISP, firewall, or other network-related problem.

**Comment by Mihaxxi** [comment]
hmm... ok. 
i'lll thinking about...
