### ISSUE TITLE
Low hashrate of video cards rtx 3050 8 GB, when mining ergo + gram + zil. 

### ISSUE THREAD

**Issue by Makimfd** [rigelminer/rigel#216]
Hello, please help me. The problem is that when mining on RTX 3050 8 GB video cards, triple mining ergo + gram + zil, the gram hashrate is very small, about 15-50 mx, but on the hashrateno website the average hashrate is about 400 mx, the only difference is the video memory vendor is micron, and my video cards are with hynix. OS - win 10, I overclocked with the MSA autoburner program and wrote the overclocking parameters in the bat file. P.S. when mining iron + gram + zil, the hashrate is good 19 mx + 950 mx + 29 mx, with 75 watts of consumption, and the photos
![photo_2024-08-04_22-06-13](https://github.com/user-attachments/assets/3d6655de-b115-4c8b-befc-fc861a88f619)
![photo_2024-08-04_22-06-16](https://github.com/user-attachments/assets/6a00e9a2-03bb-43f6-8c6a-19b3a1d7ecec)
 do not display power consumption and efficiency, even on version Rigel 1.18.1

**Comment by rigelminer** [comment]
Sometimes the auto tuner fails to find a good dual ratio (=ratio between the primary and the secondary algorithm), so try setting it manually, e.g. `--dual-mode a12:r8` (see readme for more info on syntax).

**Comment by Makimfd** [comment]
Sorry for my inattention. Thanks for your help!

**Comment by rigelminer** [comment]
No problem, and you're welcome!

Did `--dual-mode` help?

**Comment by Makimfd** [comment]
yes, --dual-mode a12:r8 helped, I also tried to configure with the command --dual-mode a12:h90 and 80-95%. but still the hashrate is lower than that of 3050 with micron memory, in my experience, hynix are always more energy-intensive, I achieved a better ratio of 65 mh, 500 mh, 30 mh.

**Comment by rigelminer** [comment]
I see. Well, at least it's performing better than it was originally. Thanks for reporting back :+1:
