### ISSUE TITLE
Xelis GPU memory usage is like 9,8Gb.

### ISSUE THREAD

**Issue by NKSoft7** [rigelminer/rigel#218]
Why on my RTX 3080 10Gb on Xelis memory usage is about 9,8Gb? And there's no room for ZIL DAG cache and it gives very low hashrate on Xelis unless option to not cache ZIL DAG  is set, which itself is bad..

**Comment by rigelminer** [comment]
`xelishashv2` can be run with any amount of memory, but using more memory usually results in higher hashrate. So caching ZIL DAG may have a negative effect. You may be better off with disabling it, depending on how much hashrate you lose leaving it on.

> which itself is bad

It's not bad. The option to disable it is there specifically for cases like this, where not caching the DAG has a benefit.

**Comment by NKSoft7** [comment]
But it appears to be, generating DAG taking the time of the ZIL round.

**Comment by rigelminer** [comment]
> generating DAG is taking the time of ZIL round

You're right. One needs to calculate what's better - leaving the cache on sacrificing XEL hashrate or turning it off and lose some ZIL. Based on the numbers you've posted, turning it off is the way to go.
I don't think you're losing much by disabling the cache. Probably less than 10% of your ZIL earnings.

**Comment by NKSoft7** [comment]
Even if it's probably 10%, it's big deal in mining nowadays!..

**Comment by rigelminer** [comment]
10% of ZIL, not your total earnings. ZIL must be what, 20% of your total revenue, which means you'd be losing ~2%. In any case, that's just the way it is - XelishashV2 works better when you give it more memory.
