### ISSUE TITLE
not play ./rigel

### ISSUE THREAD

**Issue by SeoHaKwon** [rigelminer/rigel#219]
hello, i have problem.

run this command : 
sudo ./rigel -a kawpow --coin rvn -o stratum+tcp://rvn.2miners.com:6060 -u WALLET_ADDRESS -w my_rig --log-file logs/miner.log 

but 

this error message :
./rigel: 1: Syntax error: ")" unexpected 

and 
Except for the sudo command 

./rigel -a kawpow --coin rvn -o stratum+tcp://rvn.2miners.com:6060 -u WALLET_ADDRESS -w my_rig --log-file logs/miner.log 

=> 

bash: ./rigel: cannot execute binary file: Exec format error 

Any idea how to solve this ?

**Comment by rigelminer** [comment]
Please post the output of `ls -l rigel` command

**Comment by SeoHaKwon** [comment]
> Please post the output of `ls -l rigel` command

-rwxrwxr-x 1 nvidia nvidia 84409840 Jul 19 20:40 rigel

this output

**Comment by rigelminer** [comment]
Ok, thanks. The file size is correct. Please also validate the checksum:

```
> sha256sum rigel
9c8ab50efbb30ce878a3cc225670b021d7c77f917bb2b5480b5983ffb44bb0d4  rigel
```

If it is correct, are you trying to run rigel in a VM, WSL environment, or a 32-bit OS by any chance? That wouldn't work.

**Comment by SeoHaKwon** [comment]
> Ok, thanks. The file size is correct. Please also validate the checksum:
> 
> ```
> > sha256sum rigel
> 9c8ab50efbb30ce878a3cc225670b021d7c77f917bb2b5480b5983ffb44bb0d4  rigel
> ```
> 
> If it is correct, are you trying to run rigel in a VM, WSL environment, or a 32-bit OS by any chance? That wouldn't work.

9c8ab50efbb30ce878a3cc225670b021d7c77f917bb2b5480b5983ffb44bb0d4  rigel
same validate 

and this OS ubuntu 20.04 / 64bit and not VM not WSL 
but 

bash: ./rigel: cannot execute binary file: Exec format error 

same..

**Comment by SeoHaKwon** [comment]
> What's your CPU? It's not ARM is it?

sry it's arm ,

arm is not work ?

**Comment by SeoHaKwon** [comment]
> Yeah, I'm afraid it would only work on x86_64 architecture.

thank you !
