### ISSUE TITLE
Problem with mining KarlsenhashV2 + Hoosat (Pyrinhash)

### ISSUE THREAD

**Issue by albamef** [rigelminer/rigel#222]
Miner got error at "not supported algorithm", but in version 1.8 fishhash+pyrinhash works fine.

**Comment by rigelminer** [comment]
`karlsenhashv2` can only be dual mined with `pyrinhashv2` and `sha256ton`. There's no `karlsenhashv2+pyrinhash` dual combo.

**Comment by albamef** [comment]
> `karlsenhashv2` can only be dual mined with `pyrinhashv2` and `sha256ton`. There's no `karlsenhashv2+pyrinhash` dual combo.

Can you add this feature? If karlsenhashv2 like fishhash algo it can't be difficult

**Comment by rigelminer** [comment]
I've decided against adding that combo because the HTN team is forking to another algorithm soon, and PYI is now using `pyrinhashv2`. It's not worth the effort, basically.

**Comment by albamef** [comment]
Ok, thanks
