### ISSUE TITLE
temperature targeting does not work

### ISSUE THREAD

**Issue by Airdropkin** [rigelminer/rigel#227]
When I try to set memory and core temperature targeting using the command --fan-control t:[60;84][50;30-95], I get an error in the log.
 error: Invalid value 't:[60' for '--fan-control <FAN1,FAN2,...>': failed to parse fan control settings, try wrapping the argument value in double quotes

**Comment by rigelminer** [comment]
Have you tried what the error message suggests? Passing it as `--fan-control "t:[60;84][50;30-95]"`?

**Comment by rigelminer** [comment]
No worries. The examples work most of the time but depending on the shell you're using the quotes may be required.
