### ISSUE TITLE
Catastrophic error. Help?

### ISSUE THREAD

**Issue by augustors1** [rigelminer/rigel#234]
I used rigel for long time and now I tried to use it again, same oc that I am currently using but with gminer. I just changed the miner to check if it is working better but rigel does not work anymore. Anyone can help?
![Rigel (1)](https://github.com/user-attachments/assets/14631bee-e424-4b52-ba0e-98cf254ad8f0)

**Comment by rigelminer** [comment]
Thanks for letting me know. I accidentally broke `kawpow` in 1.19.2. Please use version 1.19.1 for now.

**Comment by rigelminer** [comment]
Fixed in 1.19.3
