### ISSUE TITLE
CFX under WIN 10 not enought memory...

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#237]
Hello!

CFX under WIN 10 not enought memory for DAG file...
It is possible to fix or not?

![image](https://github.com/user-attachments/assets/2e12c233-7049-4526-b402-b5365dc41ed0)

**Comment by rigelminer** [comment]
I'm afraid DAG growing in size is part of their POW scheme. Unless CFX changes that, there isn't much I can do.
