### ISSUE TITLE
Lost hash when mining Nexa and ZIL

### ISSUE THREAD

**Issue by BSDMining** [rigelminer/rigel#24]
I'm seeing a weird issue when dual mining Nexa and Zil for the Nexa hashrate being lower than if not dual for the same OC's.  I believe we should be getting the same hash as long as it's not in the Zil window.
![image](https://user-images.githubusercontent.com/125324765/218608292-fa9482b0-f6b1-45d9-88da-6298c21f6e59.png)

**Comment by DervilRus** [comment]
I confirm!!! Sorry for the duplicate. I didn't understand the joke either. Please fix as soon as possible.

**Comment by rigelminer** [comment]
The miner needs ~7.5GB of memory for a look up table to achieve full speed on Nexa. In Nexa+Zil mode rigel caches Zil DAG making it impossible to keep both it and Nexa lookup table in memory. To circumvent this, the miner falls back to using a smaller Nexa lookup table (~2GB), however that comes at a cost of reduced hashrate.

**Comment by DervilRus** [comment]
> The miner needs ~7.5GB of memory for a look up table to achieve full speed on Nexa. In Nexa+Zil mode rigel caches Zil DAG making it impossible to keep both it and Nexa lookup table in memory. To circumvent this, the miner falls back to using a smaller Nexa lookup table (~2GB), however that comes at a cost of reduced hashrate.

Is it possible to add an option so that each time the protocol is switched, the DAG is recreated? It seems to me that it will still be less loss than cutting 10%?

**Comment by rigelminer** [comment]
Not just the DAG but the Nexa LUT too. It is certainly possible, but would require some significant internal code refactoring. I'll leave this issue open in case I have time in future to implement this.

**Comment by DervilRus** [comment]
Understood. It turns out this is a problem with cards with 8gb of memory. I originally thought it was just a glitch :) Thanks for the clarification.

**Comment by rigelminer** [comment]
Version 1.6.3 allows to circumvent this issue by disabling ZIL DAG caching, you can do that with `--zil-cache-dag on,off` (with `off` for the affected 8GB cards and `on` for all others)
