### ISSUE TITLE
GPU 13 is out of range on a 14 GPU rig

### ISSUE THREAD

**Issue by Xefier** [rigelminer/rigel#29]
On Hive OS with Extra config arguments:
-d 2,3,4,5,6,7,8,9,10,11,12,13

I get an error saying GPU 13 is out of range. No other miner has this problem on this rig, only Rigel.
I ended up having to use a different miner for the 14th GPU

**Comment by rigelminer** [comment]
Perhaps it's not seeing that GPU for some reason. Are all GPUs Nvidia? If you run without `-d`, is it using all 14?

**Comment by Xefier** [comment]
> Perhaps it's not seeing that GPU for some reason. Are all GPUs Nvidia? If you run without `-d`, is it using all 14?

The rig is x2 3060, x12 3060 Ti so all Nvidia.
Yes it works perfectly fine on all GPUs without -d, however at the moment DNX is more profitable than NEXA on 3060

**Comment by Xefier** [comment]
In-case it's relevant
Hive OS 0.6-220@230210
Nvidia Driver 525.85.05

**Comment by Xefier** [comment]
Seems to be fixed in the latest miner update, or was possibly fixed by the Hive OS CUDA update, either way it's working now.

**Comment by rigelminer** [comment]
I was really puzzled why `-d 13` wouldn't work, maybe it had something to do with how PCI address matching works between CUDA and NVML. Anyway, I'm glad the update fixed it.
