### ISSUE TITLE
nexapow+zil

### ISSUE THREAD

**Issue by DervilRus** [rigelminer/rigel#3]
After switching to zil, the miner does not return to nexa.

**Comment by rigelminer** [comment]
What pool are you mining to?

**Comment by DervilRus** [comment]
rigel.exe -a nexapow+zil ^
 	-o [1]stratum+ssl://pool.woolypooly.com:3124 -u [1]nexawallet ^
 	-o [2]zmp+ssl://eu1-zil.shardpool.io:5555 -u [2]zilwallet ^
 	-w rig --log-file logs/miner.log

**Comment by rigelminer** [comment]
Thanks. I'll look into it.

**Comment by DervilRus** [comment]
I am currently mining nexa without zil on woolypooly, everything is ok. thanks for miner

**Comment by Canefis** [comment]
> rigel.exe -a nexapow+zil ^ -o [1]stratum+ssl://pool.woolypooly.com:3124 -u [1]nexawallet ^ -o [2]zmp+ssl://eu1-zil.shardpool.io:5555 -u [2]zilwallet ^ -w rig --log-file logs/miner.log

Please specify what to type in raveos for dual mining nexa+zil. I tryed 1000 combinations, miner just continuosly reboot... does not matter what you type in additional command, any command you type, just reboot without any errors in logs....

**Comment by rigelminer** [comment]
@DervilRus Please try version 1.3.3, the issue should be fixed

**Comment by DervilRus** [comment]
> @DervilRus Please try version 1.3.3, the issue should be fixed

Launched NEXA woolypooly and ZIL shardpool. watching

**Comment by DervilRus** [comment]
Thank you! Problem solved, everything works great. The only problem left for me is a crash on one of the computers with an error on windows 10 during an ssl connection.
