### ISSUE TITLE
Support Kaspa Solo Node Mining

### ISSUE THREAD

**Issue by anazywalskyj** [rigelminer/rigel#32]
Rigel seems to get much better hashrate than other miners for kaspa! and it would be great if I could mine to my own node like node+tcp://127.0.0.1:16110
(without using stratum etc) 

This way I can run the Kaspa node on my mining rig and point the miner to 127.0.0.1

Thanks for the awesome work!

**Comment by rigelminer** [comment]
I'm afraid native solo mining won't be supported any time soon due to very low demand.
However, there are a few tools that would let you use rigel to mine to your own node:
https://github.com/onemorebsmith/kaspa-stratum-bridge
https://github.com/fungibilly/kaspad-stratum
Both are rigel-compatible.

**Comment by anazywalskyj** [comment]
Good morning!

Thanks for the reply, I will give it a shot :)

Rigel rocks!
