### ISSUE TITLE
Problem with ZIL mining and Nexa mining

### ISSUE THREAD

**Issue by albamef** [rigelminer/rigel#36]
Zil on shardpool not mining correctly. After a round of zilliqa, the miner does not switch to the main currency, but continues to mine zilliqa.

Mining NEXA on Windows on RTX 3060 Ti and RTX 3070 show "error: insufficient memory" and miner crashed. Any OC is disabled. Windows 10 1903 version, NVIDIA driver is 528.24

**Comment by rigelminer** [comment]
Those are two separate issues. I'm going to reply to the first one, as there's another ticket for the "insufficient memory" thing.
When you connect to shardpool, make sure you use zmp protocol - `zmp+ssl://eu1-zil.shardpool.io:5555`, not the generic stratum. Let me know if it fixed the issue.

**Comment by albamef** [comment]
zmp+ssl://eu1-zil.shardpool.io:5555 is work, thanks. But in Windows 22H2 I have error "insufficient memory". In lolminer with "--keepfree 1024" option works fine

**Comment by albamef** [comment]
I try Windows 10 1903, Windows 10 1809, Windows 10 21H1 and Windows 10 22H2, try drivers 528.24 and old 512.15.. My gpu: RTX 3070 Laptop, RTX 3070, RTX 3070 Ti Laptop, RTX 3070 Laptop and RTX 3060 Ti

**Comment by rigelminer** [comment]
I'm closing this issue as it was about the miner not switching to the main coin after a Zil round, which appears to be fixed.
As for the "insufficient memory" error, try increasing virtual memory size (page file). If it doesn't help, run v1.3.10 with `--kernel 1` parameter.
