### ISSUE TITLE
PSU OVC Kicks in

### ISSUE THREAD

**Issue by Strunczez** [rigelminer/rigel#38]
Hello there, I have an issue:
When miner starts all GPU's at once, GPU's are drawing too much current and PSU OVC protection kicks in crashing whole rig.
No matter if Power limit is set or not, GPU BIOS has no time to limit power if all GPU start at once.

My setup is 2x BeQuiet Dark Power Pro 1200W, each o them powering 3x RTX 3080 450W cards. Power limit is set to 250W, 
Sometime second PSU goes down and rig continues on 3 GPU. 
If both PSU do not crash, miner works flawlessly for hours / days. 
Crash occurs only when miner starts.

I have 4 rigs in this setup and each of them is crashing the same way (2 on MinerOS and 2 on HiveOS)
Other mining software works great so it is not a hardware issue.

Please provide an option to delay start of each GPU, so that they do not start all at once.

It will be nice If you also add an option to control fan speed for second / third algo.
Zil with high memory OC needs more cooling to VRAM so that it will be nice to boost fans for a Zil window.

**Comment by Strunczez** [comment]
--zfan Oh thx, ill try :)

PSU turning off is not an driver issue for sure, till 1.3.6 everything is fine. I am working on 1.3.6 now without any issues.
Drivers: 
525.85.05 on two rigs
495.46 on another two
In all of them OVC protection kicks in turning off main or auxiliary PSU.
Something changed in miner initialisation from version 1.3.6 to 1.3.7.

**Comment by Strunczez** [comment]
Please let me know if it is going to be fixed or I have to switch to lolminer? I do not want to continue on slow 1.3.6 version ... :(

**Comment by impulse709** [comment]
3 cards at 450 watts each comes to 1350 and you are running it on a 1200 watt PSU... horrible idea.

**Comment by Strunczez** [comment]
I am running a whole mining farm for years, multiple rigs, without any issues, fully automated. This kind of setup is pretty normal if cards are under powered to 250W each. Of course, only if an mining software author doses not create a buggy code pushing rig over limits without my permission. 
Please tell me. If I setup OC in Hive OS and set a power limit to 250W, why software with turned OFF OC is pushing 450W from each card? It drains 450W each just for a fraction of second, but it is enough to burn a cheap Chinese PSU.
Glad I do have a good PSU, what protects me from buggy code as Rigel has. 
It is a month + and no FIX, just a delay on each GPU start would be enough to fix it, but, I see - no one cares.

**Comment by impulse709** [comment]
you never count on your underpower alone.. but you know best im sure. you clearly know how to code extremely well too! write your own non buggy miner then. because no miner is going to protect you from yourself.

**Comment by Strunczez** [comment]
Actually, I am a coder with 20+ years of experience :) My software is used worldwide and I consider myself a good coder. 

There will be a day when I will code a miner, and for sure, I will DO NOT CHANGE any power state or settings on any GPU when USER DO NOT ENTER --> ON PURPOSE <-- any switch in command line clearly meaning that HE IS WILLING TO CHANGE POWER STATE or POWER LIMIT!!!!!

**Comment by impulse709** [comment]
you can use more then one PSU. you don't need to find a single 3000 watt one....  i run 2 corsair 850 watt PSUs in my rigs. you could run 2  1000 watt evga supernovas  or 2 1000 watt corsair RM1000s though there are likely single server PSUs out there that would cover your 1600 watt rig. i look forward to the release of your mining software im sure it will be better then anything ever released in the past and anything that will ever come after it.

**Comment by Strunczez** [comment]
I am using 2x 1200W Be Quiet Dark Power Pro!

**Comment by rigelminer** [comment]
Please try v1.4.7, the issue should be fixed

**Comment by Strunczez** [comment]
@rigelminer - good news tanks, 
I'll try it in Saturday and let you know

**Comment by Strunczez** [comment]
@rigelminer Seems that issue is solved. Started rig over 20 times without any PSU OVC kick.

Thank you very much.

It will be nice If you also add an option to control **fan speed** for second / third algo.
Zil with high memory OC needs more cooling to VRAM so that it will be nice to boost fans for a Zil window.

**Comment by rigelminer** [comment]
@Strunczez Thank you for confirming it's fixed. I apologise for not replying earlier -  I was aware of this issue but couldn't find time to fix it, unfortunately.

As for the separate fan speed control, it's on my list. For now, you can use auto-fan mode with the target temperatures set for core, memory or both (see the examples in readme) - the miner will ramp up the fan speed for the zil session automatically.
