### ISSUE TITLE
Low nexapow hashrate on GTX 10xx

### ISSUE THREAD

**Issue by WagnerBezerra2021** [rigelminer/rigel#39]
Please make the gddr5x efficient in Nexa, I have 13 1080ti and they don't do more than 15mhs and very sad because in almost all algorithms they pass 3060ti, and it is logical that there are thousands of miners who still have the 1000 series, so you would increase the DEVFEE a lot.

**Comment by rigelminer** [comment]
Could you try version 1.3.9 with your 1080ti?
I'm able to get 23.5MH with `--lock-cclock 1950 --lock-mclock 5000`.

**Comment by WagnerBezerra2021** [comment]
> Could you try version 1.3.9 with your 1080ti? I'm able to get 23.5MH with `--lock-cclock 1950 --lock-mclock 5000`.

Thanks for the quick response, I'll try, but wouldn't the ideal for a 1080 ti be at least 50mhs?

**Comment by rigelminer** [comment]
Unfortunately, Pascal is an old architecture and lacks certain features required by Nexa algorithm. It is possible to optimise for it but I doubt it'll be able to achieve more than 30MH/s.

**Comment by WagnerBezerra2021** [comment]
> Unfortunately, Pascal is an old architecture and lacks certain features required by Nexa algorithm. It is possible to optimise for it but I doubt it'll be able to achieve more than 30MH/s.

I see, I'm very grateful for your help. Keep up the great work.
