### ISSUE TITLE
SSL not supported on Windows?

### ISSUE THREAD

**Issue by Kekkonshiki** [rigelminer/rigel#4]
`2023-01-25 11:29:08] Rigel v1.3.0 - [Windows]
[2023-01-25 11:29:08] 
[2023-01-25 11:29:08] Driver: v522.25
[2023-01-25 11:29:08] 
[2023-01-25 11:29:08] + GPU #0: GeForce RTX 3080 10G
[2023-01-25 11:29:08] 
[2023-01-25 11:29:08] Pools for nexapow (dev fee 2.0%):
[2023-01-25 11:29:08] [stratum-eu.rplant.xyz:17092] connecting...
[2023-01-25 11:29:08] PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedCriticalExtension', rigel\src\miner\utils\network\ssl.rs:42:53`

**Comment by DervilRus** [comment]
Win 11 all ok, ssl work. On Win10 same error

**Comment by rigelminer** [comment]
I'm not entirely sure why this error is occurring, perhaps some issue with the windows certificate trust store? Does the error persist when you connect to an ssl stratum of another pool?
Anyway, there is `--no-strict-ssl` option in v1.3.3+ where you can disable the cert check as a temporary workaround.

**Comment by DervilRus** [comment]
--no-strict-ssl    does not solve the problem

**Comment by DervilRus** [comment]
each error occurs for each pool separately (nexa+zil)
I had to switch to a connection without ssl

stratum+tcp://pool.woolypooly.com:3124 zmp+tcp://zil.flexpool.io

**Comment by rigelminer** [comment]
@DervilRus Thank you. I hope I got to the bottom of this issue. Please try this test build (no need to set `--no-string-ssl`)
[rigel-1.3.4-cert-fix-win.zip](https://github.com/rigelminer/rigel/files/10530546/rigel-1.3.4-cert-fix-win.zip)

**Comment by DervilRus** [comment]
> @DervilRus Thank you. I hope I got to the bottom of this issue. Please try this test build (no need to set `--no-string-ssl`) [rigel-1.3.4-cert-fix-win.zip](https://github.com/rigelminer/rigel/files/10530546/rigel-1.3.4-cert-fix-win.zip)

Now everything is ok. Thank you!

**Comment by rigelminer** [comment]
This fix is published in 1.3.5, closing the issue.
