### ISSUE TITLE
Does not display cards in HiveOS

### ISSUE THREAD

**Issue by Norinivan** [rigelminer/rigel#40]
![Screenshot_1](https://user-images.githubusercontent.com/37981410/227724455-df1de905-33c0-48d2-849d-d9d0568115a7.jpg)

**Comment by Norinivan** [comment]
thx

**Comment by rigelminer** [comment]
The other person I mentioned earlier managed to solve this by upgrading to the newest stable HiveOS image:
> `hive-replace --list`
> select most recent, let it do its thing
> Let it reboot, upgrade and reboot
> done

Could you try the same?

**Comment by Norinivan** [comment]
Yes, it works. Thx!!
![Screenshot_2](https://user-images.githubusercontent.com/37981410/227740928-318d2ed6-0397-41d0-b1c7-59d902169127.jpg)

**Comment by rigelminer** [comment]
Great. Thanks for confirming that fixes the issue. I'm going to close it as resolved.
