### ISSUE TITLE
 What version of CUDA is required for the miner to work?

### ISSUE THREAD

**Issue by Quake4** [rigelminer/rigel#42]
subj

**Comment by rigelminer** [comment]
CUDA installation is not required for the miner to work. Supported video drivers are v440+.

**Comment by Quake4** [comment]
docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
10.2?

**Comment by rigelminer** [comment]
CUDA 12, but that doesn't stop the miner from running on systems with old drivers

**Comment by Quake4** [comment]
which version of cuda is the minimum supported (set when building the exe)

**Comment by Quake4** [comment]
nvcc_ARCH += -gencode=arch=compute_75,code=\"sm_75,compute_75\" # CUDA 10 req.
#nvcc_ARCH += -gencode=arch=compute_70,code=\"sm_70,compute_70\" # CUDA 9.1
#nvcc_ARCH += -gencode=arch=compute_61,code=\"sm_61,compute_61\" # CUDA 8

**Comment by rigelminer** [comment]
sm_61 (Pascal) is the oldest architecture the miner supports

**Comment by Quake4** [comment]
Cuda 8.0. as miniz. Fine.
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
Pls, write to readme this requirement.
