### ISSUE TITLE
RTX 3080 GPU#0 error: GPU overclock is too high which made it unstable

### ISSUE THREAD

**Issue by brain-5** [rigelminer/rigel#45]
Hello. Sometimes I got error: "**GPU#0 error: GPU overclock is too high which made it unstable**" only RTX 3080. I tried to clear overclock in MSI Afterburner, but it not solved problem. Also tried to reduce core clock on 50 from default, but it is same error. In other miners programs is ok. How can I fix it?
**Algo is Nexa+Zil. Rigel v1.3.11 Windows.**

```
rigel.exe -a nexapow+zil ^
-o [1]stratum+ssl://pool.woolypooly.com:3124 -u [1]Wallet ^
-o [2]stratum+tcp://eu.zil.k1pool.com:1111 -u [2]Wallet ^
-w %ComputerName% -p start=0 ^
-d 0,1 ^
-l log.txt
```

**Comment by rigelminer** [comment]
Could you try running it with `--kernel 2` and see if it fixes the problem?

**Comment by brain-5** [comment]
No. It is not fix.

**Comment by rigelminer** [comment]
I couldn't come up with a solution at the time, but if you're still affected by this issue when using newer versions of rigel, please open a new ticket.
