### ISSUE TITLE
RXD 

### ISSUE THREAD

**Issue by WagnerBezerra2021** [rigelminer/rigel#49]
please add RXD to your list, we are stuck with Bzminer.

**Comment by UselessGuru** [comment]
The algorithm for RXD is SHA512256d which is supported by various miners:

https://minerstat.com/coin/RXD/miners
https://github.com/TrailingStop/TT-Miner-release

**Comment by AionIntDevGM** [comment]
Please add RXD also! would love to see this

**Comment by rigelminer** [comment]
Added in 1.5.0
