### ISSUE TITLE
Connection timeout on Windows

### ISSUE THREAD

**Issue by Sebcrypto** [rigelminer/rigel#5]
Hello

I try your miner on windows, it's not possible to connect to the pool. i have connection timeout to pool with rplant and woolypooly pool.

Thanks

**Comment by Canefis** [comment]
Rigel has a request time out error - use 95.85.76.75:3124 instead of pool address (Europe server ip) Rigel does not always correctly pull up DNS, they will fix it in the next release.

**Comment by shmox75** [comment]
> 95.85.76.75

This resolved the issue but now I have another error :
` Dev fee connectivity error: all pools are unavailable`

**Comment by Kekkonshiki** [comment]
try the **dns-over-https** option

**Comment by rigelminer** [comment]
Please try version 1.3.3, the issue should be fixed
