### ISSUE TITLE
Alephium hashrate on the pool side

### ISSUE THREAD

**Issue by 53nsk** [rigelminer/rigel#51]
Hello @rigelminer. I've found an issue when trying to mine alephium - miner shows expected hashrate and power consumption is usual, however hashrate on the pool side is 4-5 times lower. I've tried 3 pools with the same result. Also i've noticed, that share difficulty, which is displayed in miner, is always going down to 4.30G, but number of accepted shares corresponds to 30G.
![image](https://user-images.githubusercontent.com/32919536/232669119-65893ffc-aa74-4b44-bae1-274c600a8467.png)

**Comment by rigelminer** [comment]
Hi. It's a known problem with some pools. Could you tell me what pools you tried? The miner should be working correctly with herominers.

**Comment by 53nsk** [comment]
https://alph-pool.com
https://woolypooly.com/en
https://coinhunters.space/pools/pool-alph/

**Comment by rigelminer** [comment]
Please try v1.4.6, the issue should now be fixed

**Comment by 53nsk** [comment]
In 1.4.6 mining won't start at all. Tried all previously mentioned pools as well as herominers and getting these errors:
![image](https://user-images.githubusercontent.com/32919536/236734788-15f34ecd-b942-4826-973c-fc017c631fea.png)

**Comment by rigelminer** [comment]
Weird, it's working fine for me, I just checked. Are you sure you set `-a alephium` and not some other algorithm?

**Comment by 53nsk** [comment]
My apologies, i've really forgot to change algo in bat file. Bug is fixed, miner is working fine, thanks.
