### ISSUE TITLE
how to set the timeout longer?

### ISSUE THREAD

**Issue by viponedream** [rigelminer/rigel#54]
rigel say timeout and disconnect, but bz and the other rig can mine well.
how to set it longer?

**Comment by rigelminer** [comment]
What algorithm are you mining and to what pool? Also, could you share a screenshot with the error? There are multiple types of timeouts.

**Comment by viponedream** [comment]
![(W8~@NYLAYF`I{`7PXBVKMC](https://user-images.githubusercontent.com/16624529/233837534-05432841-94e1-45d2-96cf-5a737687b8c6.png)

**Comment by viponedream** [comment]
iron
connect and submit, then say timeout

**Comment by viponedream** [comment]
the other rig works well.

**Comment by rigelminer** [comment]
Thanks. A part of the dump is hidden behind the right edge of the screenshot but things look normal based on the info I can see. The miner is telling you it didn't get a response to the first share submission. Perhaps some sort of intermittent networking issue?

**Comment by viponedream** [comment]
yearh, the reason is the miner have no response of that share submitted.  but you don't need to close the connection,
it can still mine.   the other miner just put the share to p tag.

**Comment by viponedream** [comment]
there is no need to submit the same share in a short time.

**Comment by rigelminer** [comment]
> yearh, the reason is the miner have no response of that share submitted. but you don't need to close the connection, it can still mine. the other miner just put the share to p tag.

According to the stratum protocol the pool must reply to each share submission, so when the miner detects it hasn't got a response for too long, it assumes that either the pool is malfunctioning or there's some networking issue, and the miner re-establishes a connection to make sure your GPUs don't waste electricity finding shares that don't get registered by the pool.
