### ISSUE TITLE
Reset fan speed when exit

### ISSUE THREAD

**Issue by SoulRipper888** [rigelminer/rigel#58]
Hello,

Would it be possible to reset GPU fan speed to default value when exiting Rigel?

Indeed, when I set --fan-control 70, it stays at 70% after closing Rigel.

Current system:

Windows 10 LTSC 2021
GeForce RTX 3080 with driver v528.49

Thanks in advance.

**Comment by rigelminer** [comment]
Hi. The miner will reset the fan speed if you close the miner gracefully (pressing Ctrl+C instead of clicking the X button of the terminal). Let me know if that helps.

**Comment by msclx86** [comment]
Ctrl+C is not working. When pressed, nothing happens, Rigel continues to work. Rigel 1.6.4, Windows 11 22H2 22621.1992
