### ISSUE TITLE
Low hashrate on 2000 line graphics cards

### ISSUE THREAD

**Issue by nirotub** [rigelminer/rigel#6]
Low hashrate on 2000 line graphics cards.

**Comment by buhscout** [comment]
I have 3070ti, I noticed that when the core frequency exceeds 1900mhz, then the hashrate drops by ~5% and recovers when the frequency goes down

**Comment by Canefis** [comment]
Try to increase memory lock from 5000 to 6-7000, it has been noticed, that need memory too...
