### ISSUE TITLE
GPU overclock is too high which made it unstable

### ISSUE THREAD

**Issue by peivanov** [rigelminer/rigel#64]
I am receiving "GPU overclock is too high which made it unstable" moving from 1.4.4 to 1.4.5 version.
4x3070 non LHR, clocks are as follows --lock-cclock 1550,1500,1550,1500 --cclock 400 --lock-mclock 810, PL is set to 100 in Hive.
Nvidia driver version - 525.105.17
The error is seen on all 4 cards, moving the values +-100 does not seem to have an effect.

**Comment by rigelminer** [comment]
I assume you're mining IronFish. `--cclock 400` is probably too high, try lower values starting from `--cclock 0`.

**Comment by peivanov** [comment]
Thanks for the suggestion, I`ll stick with 1.4.4 for now, the highest --cclock value I was able to set is 300 on 1.4.5 which increases the power usage by 10-12w per card for the benefit of 0.25GH/s a card with efficiency at around 136 MH/W, while on 1.4.4 I`m getting efficiency 146 MH/W.
