### ISSUE TITLE
LHR problem happens in Rigel miner 1.4.7 

### ISSUE THREAD

**Issue by redking-shuri** [rigelminer/rigel#66]
There isn't LHR problem in Rigel miner 1.4.6 & early version.
But It happens in new Rigel miner 1.4.7.

**Comment by redking-shuri** [comment]
It happens only using 525.116.03 driver.
and not happen using 525.89.02 driver.

**Comment by WagnerBezerra2021** [comment]
> There isn't LHR problem in Rigel miner 1.4.6 & early version. But It happens in new Rigel miner 1.4.7.
Not happens using 525.116.04 driver

**Comment by rigelminer** [comment]
@redking-shuri could you clarify what exactly you're experiencing? I don't think whatever you're seeing is to do with LHR because it was disabled by Nvidia.
