### ISSUE TITLE
GPUs Hashrate display issue in HIVEOS

### ISSUE THREAD

**Issue by zylovethan** [rigelminer/rigel#67]
Just refer the screen copy from my rig. The GPUs hashrate just display 1000MHs, not XXGHs. Any body face the same issue with me?
![捕获](https://github.com/rigelminer/rigel/assets/131337552/3fdf0f42-b71d-43dc-8462-5c7af5b3da8c)

**Comment by rigelminer** [comment]
Yes, it's a known HiveOS issue, see https://github.com/rigelminer/rigel/issues/57
