### ISSUE TITLE
100% CPU usage on Windows 11.

### ISSUE THREAD

**Issue by Ankain357** [rigelminer/rigel#7]
The Core i3 7300 processor is 100% loaded by the Rigel-miner in the Windows task manager. Also there is a 98% loading of virtual memory. Driver 522.25 card 3060+3060+3080, 8GB Memory, motherboard Z270-P with latest BIOS...
UPD/ Increased the swap file to 48 GB, now 53% is used, the processor is still loaded at 100%

**Comment by DervilRus** [comment]
ryzen 5 5600xб 32gb, swap file is auto. Windows 11, Msi gaming x 3060, Driver 528.24, CPU usage around 0

**Comment by SidorSidoroff** [comment]
Windows 11 pro (workstation), CPU utilization by 20%. Nvidia 522.25 drivers.. Tried all versions of your miner from 1.3.1 to 1.3.4, the result is the same, the miner loads the CPU for some reason?!

**Comment by SidorSidoroff** [comment]
Windows 11 pro (workstation), CPU utilization by 20%. Nvidia 522.25 drivers.. Tried all versions of your miner from 1.3.1 to 1.3.4, the result is the same, the miner loads the CPU for some reason?!

**Comment by SidorSidoroff** [comment]
Windows 11 pro (workstation), CPU utilization by 20%. Nvidia 522.25 drivers.. Tried all versions of your miner from 1.3.1 to 1.3.4, the result is the same, the miner loads the CPU for some reason?! AMD 3900X processor.

**Comment by SidorSidoroff** [comment]
Windows 11 pro (workstation), CPU usage by 20%. Nvidia 522.25 drivers.. Tried all versions of your miner from 1.3.1 to 1.3.4, the result is the same, the miner loads the processor for some reason?! AMD 3900X processor. There is no such problem on other bz, wildrig miners.

**Comment by SidorSidoroff** [comment]
Windows 11 pro (workstation), CPU usage by 20%. Nvidia 522.25 drivers.. Tried all versions of your miner from 1.3.1 to 1.3.4, the result is the same, the miner loads the processor for some reason?! AMD 3900X processor. There is no such problem on other bz, wildrig miners. The nexapow algorithm.

**Comment by tottexd** [comment]
I have the same problem. How to solve it? 
![r](https://user-images.githubusercontent.com/123227205/221464415-8e0f8164-9c3d-4cc1-bfbb-97edddc73db7.jpg)

**Comment by tottexd** [comment]
I had the same problem, I managed to solve it by disabling hardware acceleration
![rrr](https://user-images.githubusercontent.com/123227205/221469706-1f4abb85-265c-41cc-9e7e-a417acb101f7.jpg)
