### ISSUE TITLE
Lost hashrate 

### ISSUE THREAD

**Issue by WagnerBezerra2021** [rigelminer/rigel#70]
new rigel 1.5.0 lost performance compared to previous 1.4.8 on dual Nexa+Zil on series 3000.

**Comment by rigelminer** [comment]
Which algorithm lost performance? Could you quote some numbers 1.4.8 vs 1.5.0 and the GPUs you're running?

**Comment by WagnerBezerra2021** [comment]
lost perfomance in Nexa, little difference but lost. Decreased from 2161ghs to 2157ghs, I have 3090, 3080 ti, 3080, 3070 ti and 3060 ti.

**Comment by rigelminer** [comment]
Are you running Windows or Linux?

**Comment by WagnerBezerra2021** [comment]
Hiveos 0.6-222@230607

5.15.0-hiveos #110

N525.116.04

**Comment by rigelminer** [comment]
Thank you. I'll try to fix it asap.

**Comment by rigelminer** [comment]
Please try version 1.5.2, the issue should be fixed

**Comment by WagnerBezerra2021** [comment]
Thanks

**Comment by rigelminer** [comment]
Thanks! Please report back with the results and feel free to close the issue if it's fixed.

**Comment by WagnerBezerra2021** [comment]
I'll wait for the official release on Hiveos.
