### ISSUE TITLE
[2023-06-30 22:49:23] argument validation error: no pools set for `zil`

### ISSUE THREAD

**Issue by tolygbaby** [rigelminer/rigel#75]
@echo off
@cd /d "%~dp0"

rigel.exe -a autolykos2+sha512256d+zil ^
    -o [1]stratum+ssl://aaa.top:1180 -u [1]9hW4EeZgMghTWcg7J4ydsei8EXLbAHEDYhxafXtoC8KbHubCSwD ^
    -o [2]stratum+ssl://aaa.top:5167 -u [2]1Fz7VKWCuT1Lt7PxZ4fwfKGERAtVJo3E1E ^ 
    -o [3]zmp+ssl://aaa.top:5995 -u [3]zil1uvs90c9kmquduea8vavgcamx74950c3mlxdntc ^ 
    --cclock 100 ^
    --lock-cclock [1]1470 --lock-mclock [1]X --mclock [1]750 ^
    --lock-cclock [3]1200 --lock-mclock [3]X --mclock [3]1000 ^
    -w asusb250 --log-file logs/miner.log
pause

What's the problem?

**Comment by rigelminer** [comment]
Try putting all arguments in a single line. Issues like this typically occur when you have a whitespace after one of the `^` characters.
