### ISSUE TITLE
RTX 2060 Super 8G недостаточно памяти

### ISSUE THREAD

**Issue by asd1968** [rigelminer/rigel#76]
RTX 2060 Super 8G недостаточно памяти

**Comment by rigelminer** [comment]
Which algorithm are you mining?

**Comment by asd1968** [comment]
NexaPow

**Comment by rigelminer** [comment]
Thanks. I'll close this particular issue as a duplicate of https://github.com/rigelminer/rigel/issues/72

**Comment by asd1968** [comment]
![Снимок экрана (34)](https://github.com/rigelminer/rigel/assets/138253595/b1e8321a-adf7-4e11-a26f-1e4663826704)
