### ISSUE TITLE
1.6 with 3080 10G - error - etchash+ironfish

### ISSUE THREAD

**Issue by MonsieurKas** [rigelminer/rigel#77]
With 1.6 I get two errors and mining won't start, it keeps restarting:
I'm sual mining etchash + ironfish on ezil

see screenshot
![ApplicationFrameHost_BV7MdhY6xm](https://github.com/rigelminer/rigel/assets/35149691/31c601df-0672-4d28-8a75-b1915fcd5fde)

**Comment by rigelminer** [comment]
Thanks, I confirm it's a bug, will fix it in the next version

**Comment by rigelminer** [comment]
Fixed in 1.6.1
