### ISSUE TITLE
insufficient memory on rig with 12 RTX2060

### ISSUE THREAD

**Issue by Perfy** [rigelminer/rigel#78]
I have a rig with 12 RTX2060 cards. 
Miner fails to start with "insufficient memory" error. 
Tried kernels 1 and 2, tried to increase the swap file to 120 GB.

On a rig with 6 RTX2060 cards, the miner works fine.
![2023-07-03_135809](https://github.com/rigelminer/rigel/assets/198541/7c9ee449-a5cc-4368-a9f2-3e927c48d200)
![2023-07-03_142300](https://github.com/rigelminer/rigel/assets/198541/eea458f0-a7b1-4e4e-8831-dada327acf4b)

**Comment by rigelminer** [comment]
Can you confirm you're running rigel 1.6.1 and there are no background processes (like another miner running) that occupy GPU memory?

**Comment by Perfy** [comment]
Yes.
Yes.

**Comment by rigelminer** [comment]
Thank you. Is the issue present when you run version 1.6.0?

**Comment by Perfy** [comment]
This is an old problem.
Since version 1.3.0 (not sure).

**Comment by rigelminer** [comment]
Ok. I'm adding an option to enforce using small Nexa LUT, I'll share it here when it's ready. Let's see if it helps.

**Comment by rigelminer** [comment]
When you have time, please try running this build with `--nexapow-small-lut on` parameter set and tell me how it goes. Thank you.
[rigel-1.6.1-win.zip](https://github.com/rigelminer/rigel/files/11936306/rigel-1.6.1-win.zip)

**Comment by Perfy** [comment]
> [2023-07-03 16:56:25] GPU#8 error: insufficient memory
> [2023-07-03 16:56:25] GPU#7 error: insufficient memory
> [2023-07-03 16:56:25] GPU#4 error: insufficient memory
> [2023-07-03 16:56:25] GPU#6 error: insufficient memory
> [2023-07-03 16:56:25] GPU#3 error: insufficient memory
> [2023-07-03 16:56:25] GPU#5 error: insufficient memory
> [2023-07-03 16:56:25] GPU#2 error: insufficient memory
> [2023-07-03 16:56:25] GPU#10 error: insufficient memory
> [2023-07-03 16:56:25] GPU#0 error: insufficient memory
> [2023-07-03 16:56:25] GPU#1 error: insufficient memory
> [2023-07-03 16:56:25] GPU#9 error: insufficient memory
> [2023-07-03 16:56:25] GPU#11 error: insufficient memory
> [2023-07-03 16:56:25] all devices stopped
> [2023-07-03 16:56:25] all miner tasks finished
> [2023-07-03 16:56:25] miner terminated

**Comment by Perfy** [comment]
tried kernels 1 and 2

**Comment by rigelminer** [comment]
I'm puzzled. Does any other miner work?

**Comment by Perfy** [comment]
Yes.
Lolminer work now.

**Comment by rigelminer** [comment]
If you're willing to help me troubleshoot this, please run this version, it'll print the amount of free memory on the GPU and how much the miner needs. Run it just on one GPU, `-d 0 --nexapow-small-lut on`.
[rigel-1.6.1-lut-win.zip](https://github.com/rigelminer/rigel/files/11937517/rigel-1.6.1-lut-win.zip)

**Comment by Perfy** [comment]
[log_1.txt](https://github.com/rigelminer/rigel/files/11937719/log_1.txt)
[log_11.txt](https://github.com/rigelminer/rigel/files/11937720/log_11.txt)
[log_12.txt](https://github.com/rigelminer/rigel/files/11937721/log_12.txt)

**Comment by Perfy** [comment]
[log_11.txt](https://github.com/rigelminer/rigel/files/11937729/log_11.txt)
[log_12.txt](https://github.com/rigelminer/rigel/files/11937730/log_12.txt)
[log_1.txt](https://github.com/rigelminer/rigel/files/11937731/log_1.txt)

**Comment by rigelminer** [comment]
Yeah, I'm not entirely sure what's going on...
Could you upgrade the video driver to the newest version and try again?

**Comment by Perfy** [comment]
Updating the video driver is very problematic, because the rig is at a remote location. :)

**Comment by rigelminer** [comment]
No rush. You can try that next time you have an opportunity.
So, the miner started fine on the first 11 GPUs. What happens if you run it just on the last one (-d 11)?

**Comment by Perfy** [comment]
-d 11 - work

**Comment by rigelminer** [comment]
I guess the last one to try is to run two instances of the miner - one on GPU#0 - GPU#10, and the second one on GPU#11, haha.
I've run out of ideas to be honest. When you have a chance to upgrade the video driver, please let me know if it helped.

**Comment by Perfy** [comment]
> one on GPU#0 - GPU#10, and the second one on GPU#11

works :)

**Comment by rigelminer** [comment]
Closing this issue because there have a been a few changes that may affect it. If it still persists when using the latest version of rigel, please open a new ticket. Thank you.
