### ISSUE TITLE
Dual nexa+zil Raveos

### ISSUE THREAD

**Issue by Canefis** [rigelminer/rigel#8]
Hi there, 
I could not start dual, tryed any combos in parameters, miner just crashes and continuosly gives error: "miner "restarted after error". How to correctlt type command for dual mining... it is kinda boring.... dev said that is working dual... ☹️

**Comment by davodavodavo3** [comment]
Send me the comand you use?

**Comment by rigelminer** [comment]
There are videos on how to mine Nexa+Zil with Rigel on Youtube, for example https://www.youtube.com/watch?v=NEvJ-sUJB-c
