### ISSUE TITLE
Very Low Hashrate in nexa 3060 laptop GPU

### ISSUE THREAD

**Issue by JuniormklxD** [rigelminer/rigel#82]
I have a 3060 laptop 6G GPU and my hashrate at NEXA is locked at 6 mh/s in rigelminer, tried reinstalling drivers etc, no effect, tried other versions of rigel miner, same issue, still stuck at 6 mh/s, in other algos works fine, and using another miner with nexapow also is working fine, but i cant make it work with rigelminer on nexapow, can you take a look at it?
Windows 11, latest nvidia Driver, Rigel 1.6.3

**Comment by rigelminer** [comment]
Could you try running the miner with `--nexapow-small-lut on` and see if it helps?

**Comment by JuniormklxD** [comment]
> Could you try running the miner with `--nexapow-small-lut on` and see if it helps?

It fixed the issue, now its mining at 48 mh/s at same settings, thanks.
