### ISSUE TITLE
Low hashrate, ZIL not working

### ISSUE THREAD

**Issue by weskraft2203** [rigelminer/rigel#84]
A zil session happens once or twice, and then it stops mining zil. Version 1.7.1
On version 1.7.2, the hashrate fell. Didn't change the settings.
![1 7 1](https://github.com/rigelminer/rigel/assets/143587163/677c658d-1867-48cb-8425-6c7d312fdba9)
![1 7 2](https://github.com/rigelminer/rigel/assets/143587163/0ebc02ff-4ac6-4c49-9ef0-9a31bdfeecf3)

**Comment by rigelminer** [comment]
I know it sounds weird but could you please run the miner with `--dual-mode a12:r8.2` and confirm whether you're getting more hashrate with 1.7.2 than 1.7.1?
The actual issue here is the new version doesn't auto-tune correctly.

**Comment by weskraft2203** [comment]
Version 1.7.2 parameter --dual-mode a12:r8.2 fixed the situation. Zil earned like.
![51599638_MINIG-PC3082023_1601](https://github.com/rigelminer/rigel/assets/143587163/fdc55c0a-8445-4979-a279-c6dc9ce0aa59)

**Comment by weskraft2203** [comment]
The ZIL round is late by 15-25 seconds. May not start at all. I was able to solve the problem with mining zil only on port 50053 pool ezil

**Comment by rigelminer** [comment]
The hashrate drop issue should be fixed in 1.7.3
