### ISSUE TITLE
RTH+Zil

### ISSUE THREAD

**Issue by AlienMiner303** [rigelminer/rigel#87]
Is this a possibility to mine Rethereum+Zil?

**Comment by rigelminer** [comment]
Yes, `-a ethashb3+zil`

**Comment by AlienMiner303** [comment]
Ok so my mistake I was trying to use 1.7.1 and I need to download 1.7.2 because you have added ethashb3 support, is there an example bat file I can use in new version?

**Comment by rigelminer** [comment]
1.7.1 should work also.
See `zil-dual.bat` with multiple examples. Just replace the first algorithm with `ethashb3` and set your pools / wallet addresses.

**Comment by AlienMiner303** [comment]
K I am running test right now, I did something similar to this yesterday but was getting more rejected shares than accepted

**Comment by AlienMiner303** [comment]
Yep thank you it is working perfectly now, thanks for your help
