### ISSUE TITLE
Missing method mining.set_extranonce on ethashb3 ethstratum

### ISSUE THREAD

**Issue by cncr04s** [rigelminer/rigel#89]
failed to parse: {"jsonrpc":"2.0","id":null,"method":"mining.set_extranonce","params":["aefa",2]}

mining.set_extranonce is a required feature for most ethashb3 pools, without it this miner can not work on these pools.
ethashb3 Pools use ethstratum. but also support set extranonce on other algorithms too if possible...

**Comment by rigelminer** [comment]
Rigel does support `mining.set_extranonce`. According to the specification, the `params` array must have 1 element, not two, see https://github.com/nicehash/Specifications/blob/master/EthereumStratum_NiceHash_v1.0.0.txt#L188
As for the other algorithms, I haven't seen any reports about `mining.set_extranonce` not being supported. If you do believe there is a bug, please create a separate ticket and attach the miner log produced when running with `--log-network` if possible. Thank you.

**Comment by cncr04s** [comment]
The second parameter is the extraonce length. Every miner but this one supports it. Ignore extra parameters then, clearly simple. If not than I will not support this miner at my pool service.

**Comment by rigelminer** [comment]
> Every miner but this one supports it

Every ethashb3 pool except yours sends one element in `params` - you see, this logic is flawed. The specification was created for a reason, I suggest we follow it and be consistent. You'd only need to remove the length parameter from the params array.
