### ISSUE TITLE
v1.7.3. invalid peer certificate (SSL)

### ISSUE THREAD

**Issue by UselessGuru** [rigelminer/rigel#90]
Still the same as https://github.com/rigelminer/rigel/issues/83

I think you as the miner programmer should sort out these issues directly with the pool support.

[sha512256d.na.mine.zpool.ca:53342] connection error: invalid peer certificate contents: invalid

Command line used
`2023-09-16 19:47:23 VERBOSE: Bin\Rigel-v1.7.3\Rigel.exe --algorithm ethashb3+sha512256d --url [1]ethstratum+ssl://ethashb3.mine.zergpool.com:19996 --username [1]************************** --password [1]c=BTC,mc=RTH,ID=*************,pl=0 --worker [1]************** --url [2]stratum+ssl://sha512256d.na.mine.zpool.ca:53342 --username [2]***************************** --password [2]****************,c=BTC --worker [2]**************** --no-strict-ssl --api-bind 127.0.0.1:4002 --no-watchdog --devices 0`

Non-SSL on port 3342 is working fine.

**Comment by rigelminer** [comment]
Let's track this in https://github.com/rigelminer/rigel/issues/83 as I gave more information there
