### ISSUE TITLE
[Q] How can I mine KawPow on Nicehash and MiningRigRentals?

### ISSUE THREAD

**Issue by RainbowMiner** [rigelminer/rigel#92]
Thank you for supporting all those Kawpow coins. My question is in the subject: how to mine KawPow on Nicehash or MRR? Just use "ravencoin" as algorithm? I already tried on MRR, that resulted in "disconnected" errors.

**Comment by rigelminer** [comment]
You're welcome!

What you're describing could be a protocol compatibility issue. However, even if I fix it, unless you know in advance what coin Nicehash or MRR are going to push onto your rigs, the miner will try to mine the coin you set via `-a` parameter as dev fee, which will cause frequent DAG rebuilds.
I just tested mining `-a ravencoin` to Nicehash and I'm not seeing the disconnect errors you mentioned, but the DAG rebuilds are there. Nicehash is mining some other coin (epoch 55).

**Comment by RainbowMiner** [comment]
What that problem also refer to pools like ZergPool? That pool has a default "kawpow" to mine to and selects the most profitable coin by itself. Only, if I choose the coin myself, it would be fine, right? There are some other pools out there, who don't inform about the current coin.

The DAG rebuild occurs only, if switching between dev fee mining and normal mining, right?

**Comment by rigelminer** [comment]
> Only, if I choose the coin myself, it would be fine, right? There are some other pools out there, who don't inform about the current coin.

Yes. Mining any DAG dependent algorithm to a profit switching pool with rigel would cause this issue.

> The DAG rebuild occurs only, if switching between dev fee mining and normal mining, right?

Correct. At times when the current coin mined by the pool matches what you set in `-a` there will be no DAG rebuilds.

I guess I could alleviate the problem by mining dev fee less frequently so that the rebuilds still happen but not as often.

**Comment by RainbowMiner** [comment]
> I guess I could alleviate the problem by mining dev fee less frequently so that the rebuilds still happen but not as often.

That would be super!

**Comment by UselessGuru** [comment]
Can a larger DAG (e.g. from epoch 200) be used to mine a coin that is on epoch 100?
If so what if the miner always built the largest possible DAG using as much GPU memory possible?

**Comment by rigelminer** [comment]
@UselessGuru epoch 200 DAG's memory buffer can be re-used for epoch 100 but the data in the buffer is unique per epoch so needs to be rebuilt, or the whole DAG cached for each epoch.

**Comment by UselessGuru** [comment]
> but the data in the buffer is unique per epoch 

Too bad :-(

**Comment by rigelminer** [comment]
Added both `-a kawpow` and DAG caching in 1.13.0, see the config guide here https://github.com/rigelminer/rigel/releases/tag/1.13.0
