### ISSUE TITLE
Rigel & zergpool

### ISSUE THREAD

**Issue by PSLLSP** [rigelminer/rigel#95]
Rigel v1.8.1, Linux

Rigel doesn't have algo "kawpow" but it has several aliases, like **clore**, **neoxa**, etc. I have found in issue #92, that this parameter has impact to DAG generation. When `rigel` is connected to a mining pool that mines single coin, like [2miners](https://2miners.com/), that is not a problem. 

Zergpool is different pool, it is flexible and miner can mine coin that is most effective, so pool changes mined coin every few minutes. For example, KAWPOW can be used to mine [10 different coins in Zergpool](https://zergpool.com/site/mining?algo=kawpow)...

So, it looks like `rigel` is not good miner to mine in Zergpool. Workarround could be to limit Zergpool to mine just one coin, like other pools (password field is used to instruct pool what to mine, mc=COIN can be used to limit mining to just one coin).

Example, mine the best KAWPOW coin, pay in BTC:

```
miner -a kawpow -o "stratum+tcp://kawpow.mine.zergpool.com:3638" -u "someBTCwallet" -p "c=BTC"
```

Example, mine only CLORE coin, pay in BTC:

```
miner -a kawpow -o "stratum+tcp://kawpow.mine.zergpool.com:3638" -u "someBTCwallet" -p "c=BTC,mc=CLORE"
```

Example, mine only RVN coin, pay in RVN:

```
miner -a kawpow -o "stratum+tcp://kawpow.mine.zergpool.com:3638" -u "someRVNwallet" -p "c=RVN,mc=RVN"
```
---
I understand that `rigel` is good only for configurations with limit and it will be like this:

```
rigel -a clore -o "stratum+tcp://kawpow.mine.zergpool.com:3638" -u "someBTCwallet" -p "c=BTC,mc=CLORE"
```
```
rigel -a ravencoin -o "stratum+tcp://kawpow.mine.zergpool.com:3638" -u "someRVNwallet" -p "c=RVN,mc=RVN"
```

BTW, there are more options for password filed, like `m=solo` for solo mining, etc. The password field is "tricky"... ;-)

**Comment by Inventatorul1** [comment]
This is my only issue with rigel miner. There needs be a way to specify an algo so the pool can select the most profitable coin.

**Comment by rigelminer** [comment]
@Inventatorul1 I'm planning on fixing it soon

**Comment by PSLLSP** [comment]
Another pool that mines the best coin is [unMineable](www.unmineable.com). `Kawpow` was used to mine `RVN` for a long time but there was a recent [announcement](https://twitter.com/un_mineable/status/1744484825946268074), that coin was changed, from `RVN` to `AIPG`, and that this change almost doubles profit of miners using `kawpow` algo... Part of the announcement was information that no action is required by miners; not valid point for miners using Rigel miner... Miner cannot influence what coin is mined in unMineable pool, it is under full control of the pool administrators. Miner can only choose what algo he will use and what currency he wants to receive.

https://unmineable.com/wizard

**Comment by rigelminer** [comment]
Added both `-a kawpow` and DAG caching in 1.13.0, see the config guide here https://github.com/rigelminer/rigel/releases/tag/1.13.0
