### ISSUE TITLE
How does the DAG switch work for currencies that are not yet supported by Rigel?

### ISSUE THREAD

**Issue by UselessGuru** [rigelminer/rigel#97]
Ethash:  e.g. EGAM / ESN / EXP?
Kawpow: e.g. PAPRY / SATOX?

These currencies are not yet supported by Rigel.

How do I mine these coins and avoid the DAG switch?

**Comment by rigelminer** [comment]
You can't mine them and avoid DAG switch unless I explicitly add support for those coins
