### ISSUE TITLE
Can't get Triple mining to connect to pools for some reason.

### ISSUE THREAD

**Issue by Jinxsyns** [rigelminer/rigel#98]
I've Tried everything I know from using other mining software (first time user of rigel miner. and I have no idea how to get this working bat file below as well as screenshot of what happens when miner runs

@echo off
@cd /d "%~dp0"

:: replace the wallet addresses with your own

rigel.exe -a ethashb3+sha512256d+zil ^
    -o [1]stratum+ssl://us.crazypool.org:3553      -u x ^
    -o [2]stratum+ssl://pool.woolypooly.com:3112   -u x ^
    -o [3]stratum+ssl://us.crazypool.org:5995      -u x ^
    -w my_rig --log-file logs/miner.log

:: rth + rxd + zil (with overclock settings)
:: set core clock to 2400, unlock memory clock, and set memory clock offset to +100 for rth+rxd (algo #1+#2)
:: set core clock to 2400, unlock memory clock, and set memory clock offset to +1000 for zil (algo #3)

::rigel.exe ^
::   --a1 ethashb3   -o [1]stratum+ssl://us.crazypool.org:3553      -u x ^
::   --a2 sha512256d -o [2]stratum+ssl://pool.woolypooly.com:3112   -u x ^
::   --a3 zil        -o [3]stratum+ssl://us.crazypool.org:5995      -u x ^
::   -w my_rig --log-file logs/miner.log

pause

![Screenshot 2023-10-13 084415](https://github.com/rigelminer/rigel/assets/130711085/6d3b4ce1-7a58-49e1-ba42-c4435565078d)

**Comment by rigelminer** [comment]
A couple of things that cause the issues you're experiencing:
1. Apparently, Crazypool uses self-signed SSL certificates, so you need to pass `--no-strict-ssl` parameter to rigel to force accepting them
2. You're using the same wallet address for all three coins. Set individual addresses per-algo using prefixes like you did with pool URLs, i.e. `-u [1]RTH_WALLET -u [2]RXD_WALLET -u [3]ZIL_WALLET`

Let me know if the above helped.

**Comment by Jinxsyns** [comment]
I know with the address's I just removed them I have valid address's in when running the program and where do I put that ssl command in the file?

**Comment by rigelminer** [comment]
Anywhere, e.g. `--no-strict-ssl -w my_rig --log-file logs/miner.log`

**Comment by Jinxsyns** [comment]
so i've gotten this to happen using those commands and fixing some issues with pool url's

@echo off
@cd /d "%~dp0"

:: replace the wallet addresses with your own
 
rigel.exe -a ethashb3+sha512256d+zil ^
    -o [1]ethstratum+tcp://us.crazypool.org:3553      -u 0xe2154301861355cd3E6203e19a068F03c10b2BAA ^
    -o [2]stratum+tcp://pool.woolypooly.com:3122   -u 17tQrQLpscAmckfPCg7raHoQWirpJPLMNw ^
    -o [3]zmp+tcp://us.crazypool.org:5005      -u zil1een8xxps4s3aehha76797a8nttlej009p5ngyq ^
    -w my_rig --log-file logs/miner.log

:: rth + rxd + zil (with overclock settings)
:: set core clock to 2400, unlock memory clock, and set memory clock offset to +100 for rth+rxd (algo #1+#2)
:: set core clock to 2400, unlock memory clock, and set memory clock offset to +1000 for zil (algo #3)

::rigel.exe ^
::   --a1 ethashb3   -o [1]ethstratum+tcp://us.crazypool.org:3553      -u 0xe2154301861355cd3E6203e19a068F03c10b2BAA ^
::   --a2 sha512256d -o [2]stratum+tcp://pool.woolypooly.com:3112   -u 17tQrQLpscAmckfPCg7raHoQWirpJPLMNw ^
::   --a3 zil        -o [3]zmp+tcp://us.crazypool.org:5005          -u zil1een8xxps4s3aehha76797a8nttlej009p5ngyq ^
::  --no-strict-ssl -w my_rig --log-file logs/miner.log

pause

![Screenshot 2023-10-13 091944](https://github.com/rigelminer/rigel/assets/130711085/c32f9d00-daeb-43ca-9009-b13728123874)

**Comment by rigelminer** [comment]
> You're using the same wallet address for all three coins. Set individual addresses per-algo using prefixes like you did with pool URLs, i.e. `-u [1]RTH_WALLET -u [2]RXD_WALLET -u [3]ZIL_WALLET`

Note the prefixes [1],[2],[3] - they are mandatory. Otherwise the miner thinks you're setting the same wallet for all three algorithms, which is what's happening in your case.
