### ISSUE TITLE
Problem connecting locally with Rigel v1.9.1 - [Windows]

### ISSUE THREAD

**Issue by oopsypoo** [rigelminer/rigel#99]
I'm running a node, version 1.11.0 on Linux. When trying to connect to pool from windows miner v1.9.1 i get the following error/respond from the node/server: 
failed to parse: {"id":6,"method":"mining.subscribed","body":{"clientId":2,"graffiti":"amd160.2"}}
error: data did not match any variant of untagged enum MessageData at line 1 column 81

Linux-version runs well. Error only comes from the Windows-miners. Can you Help

**Comment by rigelminer** [comment]
Expected `mining.subscribed` message must be in the following format:
```
{"id":0,"method":"mining.subscribed","body":{"clientId":32758,"xn":"4e4265"}}
```

**Comment by oopsypoo** [comment]
Maybe I was unclear to what I'm doing:
I'm trying to run a Ironfish pool on a LAN ( v 1.11.0 on Linux). Connecting with the Linux version of the Rigel-miner is OK (using blake3/Ironfish). I can connect to a local IP. When I try to connect to the pool(LAN) with the windows-version of Rigel, I get the once before-mentioned error.

**Comment by rigelminer** [comment]
The miner behaviour should be exactly the same between the linux and windows version. Could you run both with `--log-network --log-file rigel.log` and post the log files?

**Comment by oopsypoo** [comment]
It's weird. I tried turning the firewall on/off on server, and same with the port-number. I added the attachment
[rigel.log](https://github.com/rigelminer/rigel/files/13280006/rigel.log)

**Comment by rigelminer** [comment]
Something in the environment seems to be broken. As you can see the miner keeps submitting shares but the pool never replies.
```
{"id":1,"method":"mining.submit","body":{"miningRequestId":56305,"randomness":"5c3d635a354058bf","graffiti":"00000000000000000000000000000000fb06a80000000000000000003c000000"}}
```
As for the `data did not match any variant of untagged enum MessageData` error, could you upload the log of the linux version of rigel? Then we'll see what the difference is.

**Comment by oopsypoo** [comment]
For some reason I thought I was running Linux-version of Rigel, but I'm not. I was running  Teamredminer(because I'm running AMDGPUs on the Linux-machines). Yeah there's definitely something broken on the server-side(my server). It works fine when connecting to other pools, so it has to be some kind of missconfiguration on my side. I tried lolMiner, and got it to work by removing workername from the user/wallet-string and added it as a parameter instead. Not that it makes any difference here, but apparently there are "things" that can be done to make things work. I'll try a little bit more.

**Comment by rigelminer** [comment]
I'm going to close this but if you think anything needs to be fixed in rigel, feel free to reopen the issue.
